/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CrmClientJs);
  }
}(this, function(expect, CrmClientJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CrmClientJs.ApplicationVolumeReport();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApplicationVolumeReport', function() {
    it('should create an instance of ApplicationVolumeReport', function() {
      // uncomment below and update the code to test ApplicationVolumeReport
      //var instance = new CrmClientJs.ApplicationVolumeReport();
      //expect(instance).to.be.a(CrmClientJs.ApplicationVolumeReport);
    });

    it('should have the property totalApplications (base name: "total_applications")', function() {
      // uncomment below and update the code to test the property totalApplications
      //var instance = new CrmClientJs.ApplicationVolumeReport();
      //expect(instance).to.be();
    });

    it('should have the property totalLoanAmount (base name: "total_loan_amount")', function() {
      // uncomment below and update the code to test the property totalLoanAmount
      //var instance = new CrmClientJs.ApplicationVolumeReport();
      //expect(instance).to.be();
    });

    it('should have the property averageLoanAmount (base name: "average_loan_amount")', function() {
      // uncomment below and update the code to test the property averageLoanAmount
      //var instance = new CrmClientJs.ApplicationVolumeReport();
      //expect(instance).to.be();
    });

    it('should have the property stageBreakdown (base name: "stage_breakdown")', function() {
      // uncomment below and update the code to test the property stageBreakdown
      //var instance = new CrmClientJs.ApplicationVolumeReport();
      //expect(instance).to.be();
    });

    it('should have the property timeBreakdown (base name: "time_breakdown")', function() {
      // uncomment below and update the code to test the property timeBreakdown
      //var instance = new CrmClientJs.ApplicationVolumeReport();
      //expect(instance).to.be();
    });

    it('should have the property bdBreakdown (base name: "bd_breakdown")', function() {
      // uncomment below and update the code to test the property bdBreakdown
      //var instance = new CrmClientJs.ApplicationVolumeReport();
      //expect(instance).to.be();
    });

    it('should have the property typeBreakdown (base name: "type_breakdown")', function() {
      // uncomment below and update the code to test the property typeBreakdown
      //var instance = new CrmClientJs.ApplicationVolumeReport();
      //expect(instance).to.be();
    });

  });

}));
