/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CrmClientJs);
  }
}(this, function(expect, CrmClientJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CrmClientJs.ApplicationStatusReport();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApplicationStatusReport', function() {
    it('should create an instance of ApplicationStatusReport', function() {
      // uncomment below and update the code to test ApplicationStatusReport
      //var instance = new CrmClientJs.ApplicationStatusReport();
      //expect(instance).to.be.a(CrmClientJs.ApplicationStatusReport);
    });

    it('should have the property totalActive (base name: "total_active")', function() {
      // uncomment below and update the code to test the property totalActive
      //var instance = new CrmClientJs.ApplicationStatusReport();
      //expect(instance).to.be();
    });

    it('should have the property totalSettled (base name: "total_settled")', function() {
      // uncomment below and update the code to test the property totalSettled
      //var instance = new CrmClientJs.ApplicationStatusReport();
      //expect(instance).to.be();
    });

    it('should have the property totalDeclined (base name: "total_declined")', function() {
      // uncomment below and update the code to test the property totalDeclined
      //var instance = new CrmClientJs.ApplicationStatusReport();
      //expect(instance).to.be();
    });

    it('should have the property totalWithdrawn (base name: "total_withdrawn")', function() {
      // uncomment below and update the code to test the property totalWithdrawn
      //var instance = new CrmClientJs.ApplicationStatusReport();
      //expect(instance).to.be();
    });

    it('should have the property activeByStage (base name: "active_by_stage")', function() {
      // uncomment below and update the code to test the property activeByStage
      //var instance = new CrmClientJs.ApplicationStatusReport();
      //expect(instance).to.be();
    });

    it('should have the property avgTimeInStage (base name: "avg_time_in_stage")', function() {
      // uncomment below and update the code to test the property avgTimeInStage
      //var instance = new CrmClientJs.ApplicationStatusReport();
      //expect(instance).to.be();
    });

    it('should have the property inquiryToApprovalRate (base name: "inquiry_to_approval_rate")', function() {
      // uncomment below and update the code to test the property inquiryToApprovalRate
      //var instance = new CrmClientJs.ApplicationStatusReport();
      //expect(instance).to.be();
    });

    it('should have the property approvalToSettlementRate (base name: "approval_to_settlement_rate")', function() {
      // uncomment below and update the code to test the property approvalToSettlementRate
      //var instance = new CrmClientJs.ApplicationStatusReport();
      //expect(instance).to.be();
    });

    it('should have the property overallSuccessRate (base name: "overall_success_rate")', function() {
      // uncomment below and update the code to test the property overallSuccessRate
      //var instance = new CrmClientJs.ApplicationStatusReport();
      //expect(instance).to.be();
    });

  });

}));
