/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CrmClientJs);
  }
}(this, function(expect, CrmClientJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CrmClientJs.BorrowerDetail();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BorrowerDetail', function() {
    it('should create an instance of BorrowerDetail', function() {
      // uncomment below and update the code to test BorrowerDetail
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be.a(CrmClientJs.BorrowerDetail);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "created_by")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "first_name")', function() {
      // uncomment below and update the code to test the property firstName
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "last_name")', function() {
      // uncomment below and update the code to test the property lastName
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property dateOfBirth (base name: "date_of_birth")', function() {
      // uncomment below and update the code to test the property dateOfBirth
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property residentialAddress (base name: "residential_address")', function() {
      // uncomment below and update the code to test the property residentialAddress
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property mailingAddress (base name: "mailing_address")', function() {
      // uncomment below and update the code to test the property mailingAddress
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property taxId (base name: "tax_id")', function() {
      // uncomment below and update the code to test the property taxId
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property maritalStatus (base name: "marital_status")', function() {
      // uncomment below and update the code to test the property maritalStatus
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property residencyStatus (base name: "residency_status")', function() {
      // uncomment below and update the code to test the property residencyStatus
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property employmentType (base name: "employment_type")', function() {
      // uncomment below and update the code to test the property employmentType
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property employerName (base name: "employer_name")', function() {
      // uncomment below and update the code to test the property employerName
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property employerAddress (base name: "employer_address")', function() {
      // uncomment below and update the code to test the property employerAddress
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property jobTitle (base name: "job_title")', function() {
      // uncomment below and update the code to test the property jobTitle
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property employmentDuration (base name: "employment_duration")', function() {
      // uncomment below and update the code to test the property employmentDuration
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property annualIncome (base name: "annual_income")', function() {
      // uncomment below and update the code to test the property annualIncome
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property otherIncome (base name: "other_income")', function() {
      // uncomment below and update the code to test the property otherIncome
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property monthlyExpenses (base name: "monthly_expenses")', function() {
      // uncomment below and update the code to test the property monthlyExpenses
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property bankName (base name: "bank_name")', function() {
      // uncomment below and update the code to test the property bankName
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property bankAccountName (base name: "bank_account_name")', function() {
      // uncomment below and update the code to test the property bankAccountName
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property bankAccountNumber (base name: "bank_account_number")', function() {
      // uncomment below and update the code to test the property bankAccountNumber
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property bankBsb (base name: "bank_bsb")', function() {
      // uncomment below and update the code to test the property bankBsb
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property referralSource (base name: "referral_source")', function() {
      // uncomment below and update the code to test the property referralSource
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property notesText (base name: "notes_text")', function() {
      // uncomment below and update the code to test the property notesText
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property isCompany (base name: "is_company")', function() {
      // uncomment below and update the code to test the property isCompany
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property companyName (base name: "company_name")', function() {
      // uncomment below and update the code to test the property companyName
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property companyAbn (base name: "company_abn")', function() {
      // uncomment below and update the code to test the property companyAbn
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property companyAcn (base name: "company_acn")', function() {
      // uncomment below and update the code to test the property companyAcn
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property companyAddress (base name: "company_address")', function() {
      // uncomment below and update the code to test the property companyAddress
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

    it('should have the property user (base name: "user")', function() {
      // uncomment below and update the code to test the property user
      //var instance = new CrmClientJs.BorrowerDetail();
      //expect(instance).to.be();
    });

  });

}));
