/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CrmClientJs);
  }
}(this, function(expect, CrmClientJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CrmClientJs.BorrowerFinancialSummary();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BorrowerFinancialSummary', function() {
    it('should create an instance of BorrowerFinancialSummary', function() {
      // uncomment below and update the code to test BorrowerFinancialSummary
      //var instance = new CrmClientJs.BorrowerFinancialSummary();
      //expect(instance).to.be.a(CrmClientJs.BorrowerFinancialSummary);
    });

    it('should have the property totalApplications (base name: "total_applications")', function() {
      // uncomment below and update the code to test the property totalApplications
      //var instance = new CrmClientJs.BorrowerFinancialSummary();
      //expect(instance).to.be();
    });

    it('should have the property totalFunded (base name: "total_funded")', function() {
      // uncomment below and update the code to test the property totalFunded
      //var instance = new CrmClientJs.BorrowerFinancialSummary();
      //expect(instance).to.be();
    });

    it('should have the property activeLoans (base name: "active_loans")', function() {
      // uncomment below and update the code to test the property activeLoans
      //var instance = new CrmClientJs.BorrowerFinancialSummary();
      //expect(instance).to.be();
    });

    it('should have the property activeLoanAmount (base name: "active_loan_amount")', function() {
      // uncomment below and update the code to test the property activeLoanAmount
      //var instance = new CrmClientJs.BorrowerFinancialSummary();
      //expect(instance).to.be();
    });

    it('should have the property completedLoans (base name: "completed_loans")', function() {
      // uncomment below and update the code to test the property completedLoans
      //var instance = new CrmClientJs.BorrowerFinancialSummary();
      //expect(instance).to.be();
    });

    it('should have the property completedLoanAmount (base name: "completed_loan_amount")', function() {
      // uncomment below and update the code to test the property completedLoanAmount
      //var instance = new CrmClientJs.BorrowerFinancialSummary();
      //expect(instance).to.be();
    });

  });

}));
