/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CrmClientJs);
  }
}(this, function(expect, CrmClientJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CrmClientJs.Notification();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Notification', function() {
    it('should create an instance of Notification', function() {
      // uncomment below and update the code to test Notification
      //var instance = new CrmClientJs.Notification();
      //expect(instance).to.be.a(CrmClientJs.Notification);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new CrmClientJs.Notification();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new CrmClientJs.Notification();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instance = new CrmClientJs.Notification();
      //expect(instance).to.be();
    });

    it('should have the property notificationType (base name: "notification_type")', function() {
      // uncomment below and update the code to test the property notificationType
      //var instance = new CrmClientJs.Notification();
      //expect(instance).to.be();
    });

    it('should have the property relatedObjectId (base name: "related_object_id")', function() {
      // uncomment below and update the code to test the property relatedObjectId
      //var instance = new CrmClientJs.Notification();
      //expect(instance).to.be();
    });

    it('should have the property relatedObjectType (base name: "related_object_type")', function() {
      // uncomment below and update the code to test the property relatedObjectType
      //var instance = new CrmClientJs.Notification();
      //expect(instance).to.be();
    });

    it('should have the property isRead (base name: "is_read")', function() {
      // uncomment below and update the code to test the property isRead
      //var instance = new CrmClientJs.Notification();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new CrmClientJs.Notification();
      //expect(instance).to.be();
    });

    it('should have the property readAt (base name: "read_at")', function() {
      // uncomment below and update the code to test the property readAt
      //var instance = new CrmClientJs.Notification();
      //expect(instance).to.be();
    });

    it('should have the property user (base name: "user")', function() {
      // uncomment below and update the code to test the property user
      //var instance = new CrmClientJs.Notification();
      //expect(instance).to.be();
    });

  });

}));
