/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CrmClientJs);
  }
}(this, function(expect, CrmClientJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CrmClientJs.NotificationPreference();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NotificationPreference', function() {
    it('should create an instance of NotificationPreference', function() {
      // uncomment below and update the code to test NotificationPreference
      //var instance = new CrmClientJs.NotificationPreference();
      //expect(instance).to.be.a(CrmClientJs.NotificationPreference);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new CrmClientJs.NotificationPreference();
      //expect(instance).to.be();
    });

    it('should have the property applicationStatusInApp (base name: "application_status_in_app")', function() {
      // uncomment below and update the code to test the property applicationStatusInApp
      //var instance = new CrmClientJs.NotificationPreference();
      //expect(instance).to.be();
    });

    it('should have the property repaymentUpcomingInApp (base name: "repayment_upcoming_in_app")', function() {
      // uncomment below and update the code to test the property repaymentUpcomingInApp
      //var instance = new CrmClientJs.NotificationPreference();
      //expect(instance).to.be();
    });

    it('should have the property repaymentOverdueInApp (base name: "repayment_overdue_in_app")', function() {
      // uncomment below and update the code to test the property repaymentOverdueInApp
      //var instance = new CrmClientJs.NotificationPreference();
      //expect(instance).to.be();
    });

    it('should have the property noteReminderInApp (base name: "note_reminder_in_app")', function() {
      // uncomment below and update the code to test the property noteReminderInApp
      //var instance = new CrmClientJs.NotificationPreference();
      //expect(instance).to.be();
    });

    it('should have the property documentUploadedInApp (base name: "document_uploaded_in_app")', function() {
      // uncomment below and update the code to test the property documentUploadedInApp
      //var instance = new CrmClientJs.NotificationPreference();
      //expect(instance).to.be();
    });

    it('should have the property signatureRequiredInApp (base name: "signature_required_in_app")', function() {
      // uncomment below and update the code to test the property signatureRequiredInApp
      //var instance = new CrmClientJs.NotificationPreference();
      //expect(instance).to.be();
    });

    it('should have the property systemInApp (base name: "system_in_app")', function() {
      // uncomment below and update the code to test the property systemInApp
      //var instance = new CrmClientJs.NotificationPreference();
      //expect(instance).to.be();
    });

    it('should have the property applicationStatusEmail (base name: "application_status_email")', function() {
      // uncomment below and update the code to test the property applicationStatusEmail
      //var instance = new CrmClientJs.NotificationPreference();
      //expect(instance).to.be();
    });

    it('should have the property repaymentUpcomingEmail (base name: "repayment_upcoming_email")', function() {
      // uncomment below and update the code to test the property repaymentUpcomingEmail
      //var instance = new CrmClientJs.NotificationPreference();
      //expect(instance).to.be();
    });

    it('should have the property repaymentOverdueEmail (base name: "repayment_overdue_email")', function() {
      // uncomment below and update the code to test the property repaymentOverdueEmail
      //var instance = new CrmClientJs.NotificationPreference();
      //expect(instance).to.be();
    });

    it('should have the property noteReminderEmail (base name: "note_reminder_email")', function() {
      // uncomment below and update the code to test the property noteReminderEmail
      //var instance = new CrmClientJs.NotificationPreference();
      //expect(instance).to.be();
    });

    it('should have the property documentUploadedEmail (base name: "document_uploaded_email")', function() {
      // uncomment below and update the code to test the property documentUploadedEmail
      //var instance = new CrmClientJs.NotificationPreference();
      //expect(instance).to.be();
    });

    it('should have the property signatureRequiredEmail (base name: "signature_required_email")', function() {
      // uncomment below and update the code to test the property signatureRequiredEmail
      //var instance = new CrmClientJs.NotificationPreference();
      //expect(instance).to.be();
    });

    it('should have the property systemEmail (base name: "system_email")', function() {
      // uncomment below and update the code to test the property systemEmail
      //var instance = new CrmClientJs.NotificationPreference();
      //expect(instance).to.be();
    });

    it('should have the property dailyDigest (base name: "daily_digest")', function() {
      // uncomment below and update the code to test the property dailyDigest
      //var instance = new CrmClientJs.NotificationPreference();
      //expect(instance).to.be();
    });

    it('should have the property weeklyDigest (base name: "weekly_digest")', function() {
      // uncomment below and update the code to test the property weeklyDigest
      //var instance = new CrmClientJs.NotificationPreference();
      //expect(instance).to.be();
    });

  });

}));
