/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CrmClientJs);
  }
}(this, function(expect, CrmClientJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CrmClientJs.BrokersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BrokersApi', function() {
    describe('brokersApplicationsRetrieve', function() {
      it('should call brokersApplicationsRetrieve successfully', function(done) {
        //uncomment below and update the code to test brokersApplicationsRetrieve
        //instance.brokersApplicationsRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('brokersBdmsApplicationsRetrieve', function() {
      it('should call brokersBdmsApplicationsRetrieve successfully', function(done) {
        //uncomment below and update the code to test brokersBdmsApplicationsRetrieve
        //instance.brokersBdmsApplicationsRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('brokersBdmsCreate', function() {
      it('should call brokersBdmsCreate successfully', function(done) {
        //uncomment below and update the code to test brokersBdmsCreate
        //instance.brokersBdmsCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('brokersBdmsDestroy', function() {
      it('should call brokersBdmsDestroy successfully', function(done) {
        //uncomment below and update the code to test brokersBdmsDestroy
        //instance.brokersBdmsDestroy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('brokersBdmsList', function() {
      it('should call brokersBdmsList successfully', function(done) {
        //uncomment below and update the code to test brokersBdmsList
        //instance.brokersBdmsList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('brokersBdmsPartialUpdate', function() {
      it('should call brokersBdmsPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test brokersBdmsPartialUpdate
        //instance.brokersBdmsPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('brokersBdmsRetrieve', function() {
      it('should call brokersBdmsRetrieve successfully', function(done) {
        //uncomment below and update the code to test brokersBdmsRetrieve
        //instance.brokersBdmsRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('brokersBdmsUpdate', function() {
      it('should call brokersBdmsUpdate successfully', function(done) {
        //uncomment below and update the code to test brokersBdmsUpdate
        //instance.brokersBdmsUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('brokersBranchesBdmsRetrieve', function() {
      it('should call brokersBranchesBdmsRetrieve successfully', function(done) {
        //uncomment below and update the code to test brokersBranchesBdmsRetrieve
        //instance.brokersBranchesBdmsRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('brokersBranchesBrokersRetrieve', function() {
      it('should call brokersBranchesBrokersRetrieve successfully', function(done) {
        //uncomment below and update the code to test brokersBranchesBrokersRetrieve
        //instance.brokersBranchesBrokersRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('brokersBranchesCreate', function() {
      it('should call brokersBranchesCreate successfully', function(done) {
        //uncomment below and update the code to test brokersBranchesCreate
        //instance.brokersBranchesCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('brokersBranchesDestroy', function() {
      it('should call brokersBranchesDestroy successfully', function(done) {
        //uncomment below and update the code to test brokersBranchesDestroy
        //instance.brokersBranchesDestroy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('brokersBranchesList', function() {
      it('should call brokersBranchesList successfully', function(done) {
        //uncomment below and update the code to test brokersBranchesList
        //instance.brokersBranchesList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('brokersBranchesPartialUpdate', function() {
      it('should call brokersBranchesPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test brokersBranchesPartialUpdate
        //instance.brokersBranchesPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('brokersBranchesRetrieve', function() {
      it('should call brokersBranchesRetrieve successfully', function(done) {
        //uncomment below and update the code to test brokersBranchesRetrieve
        //instance.brokersBranchesRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('brokersBranchesUpdate', function() {
      it('should call brokersBranchesUpdate successfully', function(done) {
        //uncomment below and update the code to test brokersBranchesUpdate
        //instance.brokersBranchesUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('brokersCreate', function() {
      it('should call brokersCreate successfully', function(done) {
        //uncomment below and update the code to test brokersCreate
        //instance.brokersCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('brokersDestroy', function() {
      it('should call brokersDestroy successfully', function(done) {
        //uncomment below and update the code to test brokersDestroy
        //instance.brokersDestroy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('brokersList', function() {
      it('should call brokersList successfully', function(done) {
        //uncomment below and update the code to test brokersList
        //instance.brokersList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('brokersPartialUpdate', function() {
      it('should call brokersPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test brokersPartialUpdate
        //instance.brokersPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('brokersRetrieve', function() {
      it('should call brokersRetrieve successfully', function(done) {
        //uncomment below and update the code to test brokersRetrieve
        //instance.brokersRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('brokersStatsRetrieve', function() {
      it('should call brokersStatsRetrieve successfully', function(done) {
        //uncomment below and update the code to test brokersStatsRetrieve
        //instance.brokersStatsRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('brokersUpdate', function() {
      it('should call brokersUpdate successfully', function(done) {
        //uncomment below and update the code to test brokersUpdate
        //instance.brokersUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
