/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApplicationSignature model module.
 * @module models/ApplicationSignature
 * @version 1.0.0
 */
class ApplicationSignature {
    /**
     * Constructs a new <code>ApplicationSignature</code>.
     * Serializer for application signature
     * @alias module:models/ApplicationSignature
     * @param signature {String} 
     * @param name {String} 
     */
    constructor(signature, name) { 
        
        ApplicationSignature.initialize(this, signature, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, signature, name) { 
        obj['signature'] = signature;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>ApplicationSignature</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/ApplicationSignature} obj Optional instance to populate.
     * @return {module:models/ApplicationSignature} The populated <code>ApplicationSignature</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplicationSignature();

            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('signature_date')) {
                obj['signature_date'] = ApiClient.convertToType(data['signature_date'], 'Date');
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApplicationSignature</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApplicationSignature</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApplicationSignature.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['signature'] && !(typeof data['signature'] === 'string' || data['signature'] instanceof String)) {
            throw new Error("Expected the field `signature` to be a primitive type in the JSON string but got " + data['signature']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['notes'] && !(typeof data['notes'] === 'string' || data['notes'] instanceof String)) {
            throw new Error("Expected the field `notes` to be a primitive type in the JSON string but got " + data['notes']);
        }

        return true;
    }


}

ApplicationSignature.RequiredProperties = ["signature", "name"];

/**
 * @member {String} signature
 */
ApplicationSignature.prototype['signature'] = undefined;

/**
 * @member {String} name
 */
ApplicationSignature.prototype['name'] = undefined;

/**
 * @member {Date} signature_date
 */
ApplicationSignature.prototype['signature_date'] = undefined;

/**
 * @member {String} notes
 */
ApplicationSignature.prototype['notes'] = undefined;






export default ApplicationSignature;

