/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApplicationBorrowerRequest model module.
 * @module models/ApplicationBorrowerRequest
 * @version 1.0.0
 */
class ApplicationBorrowerRequest {
    /**
     * Constructs a new <code>ApplicationBorrowerRequest</code>.
     * @alias module:models/ApplicationBorrowerRequest
     * @param borrowerIds {Array.<Number>} 
     */
    constructor(borrowerIds) { 
        
        ApplicationBorrowerRequest.initialize(this, borrowerIds);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, borrowerIds) { 
        obj['borrower_ids'] = borrowerIds;
    }

    /**
     * Constructs a <code>ApplicationBorrowerRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/ApplicationBorrowerRequest} obj Optional instance to populate.
     * @return {module:models/ApplicationBorrowerRequest} The populated <code>ApplicationBorrowerRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplicationBorrowerRequest();

            if (data.hasOwnProperty('borrower_ids')) {
                obj['borrower_ids'] = ApiClient.convertToType(data['borrower_ids'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApplicationBorrowerRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApplicationBorrowerRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApplicationBorrowerRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['borrower_ids'])) {
            throw new Error("Expected the field `borrower_ids` to be an array in the JSON data but got " + data['borrower_ids']);
        }

        return true;
    }


}

ApplicationBorrowerRequest.RequiredProperties = ["borrower_ids"];

/**
 * @member {Array.<Number>} borrower_ids
 */
ApplicationBorrowerRequest.prototype['borrower_ids'] = undefined;






export default ApplicationBorrowerRequest;

