/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApplicationCreateApplicationType from './ApplicationCreateApplicationType';
import Borrower from './Borrower';
import CompanyBorrower from './CompanyBorrower';
import FundingCalculationInput from './FundingCalculationInput';
import Guarantor from './Guarantor';
import RepaymentFrequencyEnum from './RepaymentFrequencyEnum';
import StageEnum from './StageEnum';

/**
 * The ApplicationCreate model module.
 * @module models/ApplicationCreate
 * @version 1.0.0
 */
class ApplicationCreate {
    /**
     * Constructs a new <code>ApplicationCreate</code>.
     * @alias module:models/ApplicationCreate
     * @param id {Number} 
     * @param branchId {Number} 
     * @param bdId {Number} 
     */
    constructor(id, branchId, bdId) { 
        
        ApplicationCreate.initialize(this, id, branchId, bdId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, branchId, bdId) { 
        obj['id'] = id;
        obj['branch_id'] = branchId;
        obj['bd_id'] = bdId;
    }

    /**
     * Constructs a <code>ApplicationCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/ApplicationCreate} obj Optional instance to populate.
     * @return {module:models/ApplicationCreate} The populated <code>ApplicationCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplicationCreate();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('reference_number')) {
                obj['reference_number'] = ApiClient.convertToType(data['reference_number'], 'String');
            }
            if (data.hasOwnProperty('loan_amount')) {
                obj['loan_amount'] = ApiClient.convertToType(data['loan_amount'], 'Number');
            }
            if (data.hasOwnProperty('loan_term')) {
                obj['loan_term'] = ApiClient.convertToType(data['loan_term'], 'Number');
            }
            if (data.hasOwnProperty('interest_rate')) {
                obj['interest_rate'] = ApiClient.convertToType(data['interest_rate'], 'Number');
            }
            if (data.hasOwnProperty('purpose')) {
                obj['purpose'] = ApiClient.convertToType(data['purpose'], 'String');
            }
            if (data.hasOwnProperty('repayment_frequency')) {
                obj['repayment_frequency'] = RepaymentFrequencyEnum.constructFromObject(data['repayment_frequency']);
            }
            if (data.hasOwnProperty('application_type')) {
                obj['application_type'] = ApplicationCreateApplicationType.constructFromObject(data['application_type']);
            }
            if (data.hasOwnProperty('product_id')) {
                obj['product_id'] = ApiClient.convertToType(data['product_id'], 'String');
            }
            if (data.hasOwnProperty('estimated_settlement_date')) {
                obj['estimated_settlement_date'] = ApiClient.convertToType(data['estimated_settlement_date'], 'Date');
            }
            if (data.hasOwnProperty('stage')) {
                obj['stage'] = StageEnum.constructFromObject(data['stage']);
            }
            if (data.hasOwnProperty('branch_id')) {
                obj['branch_id'] = ApiClient.convertToType(data['branch_id'], 'Number');
            }
            if (data.hasOwnProperty('bd_id')) {
                obj['bd_id'] = ApiClient.convertToType(data['bd_id'], 'Number');
            }
            if (data.hasOwnProperty('borrowers')) {
                obj['borrowers'] = ApiClient.convertToType(data['borrowers'], [Borrower]);
            }
            if (data.hasOwnProperty('guarantors')) {
                obj['guarantors'] = ApiClient.convertToType(data['guarantors'], [Guarantor]);
            }
            if (data.hasOwnProperty('company_borrowers')) {
                obj['company_borrowers'] = ApiClient.convertToType(data['company_borrowers'], [CompanyBorrower]);
            }
            if (data.hasOwnProperty('security_address')) {
                obj['security_address'] = ApiClient.convertToType(data['security_address'], 'String');
            }
            if (data.hasOwnProperty('security_type')) {
                obj['security_type'] = ApiClient.convertToType(data['security_type'], 'String');
            }
            if (data.hasOwnProperty('security_value')) {
                obj['security_value'] = ApiClient.convertToType(data['security_value'], 'Number');
            }
            if (data.hasOwnProperty('valuer_company_name')) {
                obj['valuer_company_name'] = ApiClient.convertToType(data['valuer_company_name'], 'String');
            }
            if (data.hasOwnProperty('valuer_contact_name')) {
                obj['valuer_contact_name'] = ApiClient.convertToType(data['valuer_contact_name'], 'String');
            }
            if (data.hasOwnProperty('valuer_phone')) {
                obj['valuer_phone'] = ApiClient.convertToType(data['valuer_phone'], 'String');
            }
            if (data.hasOwnProperty('valuer_email')) {
                obj['valuer_email'] = ApiClient.convertToType(data['valuer_email'], 'String');
            }
            if (data.hasOwnProperty('qs_company_name')) {
                obj['qs_company_name'] = ApiClient.convertToType(data['qs_company_name'], 'String');
            }
            if (data.hasOwnProperty('qs_contact_name')) {
                obj['qs_contact_name'] = ApiClient.convertToType(data['qs_contact_name'], 'String');
            }
            if (data.hasOwnProperty('qs_phone')) {
                obj['qs_phone'] = ApiClient.convertToType(data['qs_phone'], 'String');
            }
            if (data.hasOwnProperty('qs_email')) {
                obj['qs_email'] = ApiClient.convertToType(data['qs_email'], 'String');
            }
            if (data.hasOwnProperty('funding_calculation_input')) {
                obj['funding_calculation_input'] = FundingCalculationInput.constructFromObject(data['funding_calculation_input']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApplicationCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApplicationCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApplicationCreate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['reference_number'] && !(typeof data['reference_number'] === 'string' || data['reference_number'] instanceof String)) {
            throw new Error("Expected the field `reference_number` to be a primitive type in the JSON string but got " + data['reference_number']);
        }
        // ensure the json data is a string
        if (data['loan_amount'] && !(typeof data['loan_amount'] === 'string' || data['loan_amount'] instanceof String)) {
            throw new Error("Expected the field `loan_amount` to be a primitive type in the JSON string but got " + data['loan_amount']);
        }
        // ensure the json data is a string
        if (data['interest_rate'] && !(typeof data['interest_rate'] === 'string' || data['interest_rate'] instanceof String)) {
            throw new Error("Expected the field `interest_rate` to be a primitive type in the JSON string but got " + data['interest_rate']);
        }
        // ensure the json data is a string
        if (data['purpose'] && !(typeof data['purpose'] === 'string' || data['purpose'] instanceof String)) {
            throw new Error("Expected the field `purpose` to be a primitive type in the JSON string but got " + data['purpose']);
        }
        // validate the optional field `application_type`
        if (data['application_type']) { // data not null
          ApplicationCreateApplicationType.validateJSON(data['application_type']);
        }
        // ensure the json data is a string
        if (data['product_id'] && !(typeof data['product_id'] === 'string' || data['product_id'] instanceof String)) {
            throw new Error("Expected the field `product_id` to be a primitive type in the JSON string but got " + data['product_id']);
        }
        if (data['borrowers']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['borrowers'])) {
                throw new Error("Expected the field `borrowers` to be an array in the JSON data but got " + data['borrowers']);
            }
            // validate the optional field `borrowers` (array)
            for (const item of data['borrowers']) {
                Borrower.validateJSON(item);
            };
        }
        if (data['guarantors']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['guarantors'])) {
                throw new Error("Expected the field `guarantors` to be an array in the JSON data but got " + data['guarantors']);
            }
            // validate the optional field `guarantors` (array)
            for (const item of data['guarantors']) {
                Guarantor.validateJSON(item);
            };
        }
        if (data['company_borrowers']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['company_borrowers'])) {
                throw new Error("Expected the field `company_borrowers` to be an array in the JSON data but got " + data['company_borrowers']);
            }
            // validate the optional field `company_borrowers` (array)
            for (const item of data['company_borrowers']) {
                CompanyBorrower.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['security_address'] && !(typeof data['security_address'] === 'string' || data['security_address'] instanceof String)) {
            throw new Error("Expected the field `security_address` to be a primitive type in the JSON string but got " + data['security_address']);
        }
        // ensure the json data is a string
        if (data['security_type'] && !(typeof data['security_type'] === 'string' || data['security_type'] instanceof String)) {
            throw new Error("Expected the field `security_type` to be a primitive type in the JSON string but got " + data['security_type']);
        }
        // ensure the json data is a string
        if (data['security_value'] && !(typeof data['security_value'] === 'string' || data['security_value'] instanceof String)) {
            throw new Error("Expected the field `security_value` to be a primitive type in the JSON string but got " + data['security_value']);
        }
        // ensure the json data is a string
        if (data['valuer_company_name'] && !(typeof data['valuer_company_name'] === 'string' || data['valuer_company_name'] instanceof String)) {
            throw new Error("Expected the field `valuer_company_name` to be a primitive type in the JSON string but got " + data['valuer_company_name']);
        }
        // ensure the json data is a string
        if (data['valuer_contact_name'] && !(typeof data['valuer_contact_name'] === 'string' || data['valuer_contact_name'] instanceof String)) {
            throw new Error("Expected the field `valuer_contact_name` to be a primitive type in the JSON string but got " + data['valuer_contact_name']);
        }
        // ensure the json data is a string
        if (data['valuer_phone'] && !(typeof data['valuer_phone'] === 'string' || data['valuer_phone'] instanceof String)) {
            throw new Error("Expected the field `valuer_phone` to be a primitive type in the JSON string but got " + data['valuer_phone']);
        }
        // ensure the json data is a string
        if (data['valuer_email'] && !(typeof data['valuer_email'] === 'string' || data['valuer_email'] instanceof String)) {
            throw new Error("Expected the field `valuer_email` to be a primitive type in the JSON string but got " + data['valuer_email']);
        }
        // ensure the json data is a string
        if (data['qs_company_name'] && !(typeof data['qs_company_name'] === 'string' || data['qs_company_name'] instanceof String)) {
            throw new Error("Expected the field `qs_company_name` to be a primitive type in the JSON string but got " + data['qs_company_name']);
        }
        // ensure the json data is a string
        if (data['qs_contact_name'] && !(typeof data['qs_contact_name'] === 'string' || data['qs_contact_name'] instanceof String)) {
            throw new Error("Expected the field `qs_contact_name` to be a primitive type in the JSON string but got " + data['qs_contact_name']);
        }
        // ensure the json data is a string
        if (data['qs_phone'] && !(typeof data['qs_phone'] === 'string' || data['qs_phone'] instanceof String)) {
            throw new Error("Expected the field `qs_phone` to be a primitive type in the JSON string but got " + data['qs_phone']);
        }
        // ensure the json data is a string
        if (data['qs_email'] && !(typeof data['qs_email'] === 'string' || data['qs_email'] instanceof String)) {
            throw new Error("Expected the field `qs_email` to be a primitive type in the JSON string but got " + data['qs_email']);
        }
        // validate the optional field `funding_calculation_input`
        if (data['funding_calculation_input']) { // data not null
          FundingCalculationInput.validateJSON(data['funding_calculation_input']);
        }

        return true;
    }


}

ApplicationCreate.RequiredProperties = ["id", "branch_id", "bd_id"];

/**
 * @member {Number} id
 */
ApplicationCreate.prototype['id'] = undefined;

/**
 * @member {String} reference_number
 */
ApplicationCreate.prototype['reference_number'] = undefined;

/**
 * @member {Number} loan_amount
 */
ApplicationCreate.prototype['loan_amount'] = undefined;

/**
 * Loan term in months
 * @member {Number} loan_term
 */
ApplicationCreate.prototype['loan_term'] = undefined;

/**
 * @member {Number} interest_rate
 */
ApplicationCreate.prototype['interest_rate'] = undefined;

/**
 * @member {String} purpose
 */
ApplicationCreate.prototype['purpose'] = undefined;

/**
 * @member {module:models/RepaymentFrequencyEnum} repayment_frequency
 */
ApplicationCreate.prototype['repayment_frequency'] = undefined;

/**
 * @member {module:models/ApplicationCreateApplicationType} application_type
 */
ApplicationCreate.prototype['application_type'] = undefined;

/**
 * @member {String} product_id
 */
ApplicationCreate.prototype['product_id'] = undefined;

/**
 * @member {Date} estimated_settlement_date
 */
ApplicationCreate.prototype['estimated_settlement_date'] = undefined;

/**
 * @member {module:models/StageEnum} stage
 */
ApplicationCreate.prototype['stage'] = undefined;

/**
 * @member {Number} branch_id
 */
ApplicationCreate.prototype['branch_id'] = undefined;

/**
 * @member {Number} bd_id
 */
ApplicationCreate.prototype['bd_id'] = undefined;

/**
 * @member {Array.<module:models/Borrower>} borrowers
 */
ApplicationCreate.prototype['borrowers'] = undefined;

/**
 * @member {Array.<module:models/Guarantor>} guarantors
 */
ApplicationCreate.prototype['guarantors'] = undefined;

/**
 * @member {Array.<module:models/CompanyBorrower>} company_borrowers
 */
ApplicationCreate.prototype['company_borrowers'] = undefined;

/**
 * @member {String} security_address
 */
ApplicationCreate.prototype['security_address'] = undefined;

/**
 * @member {String} security_type
 */
ApplicationCreate.prototype['security_type'] = undefined;

/**
 * @member {Number} security_value
 */
ApplicationCreate.prototype['security_value'] = undefined;

/**
 * @member {String} valuer_company_name
 */
ApplicationCreate.prototype['valuer_company_name'] = undefined;

/**
 * @member {String} valuer_contact_name
 */
ApplicationCreate.prototype['valuer_contact_name'] = undefined;

/**
 * @member {String} valuer_phone
 */
ApplicationCreate.prototype['valuer_phone'] = undefined;

/**
 * @member {String} valuer_email
 */
ApplicationCreate.prototype['valuer_email'] = undefined;

/**
 * @member {String} qs_company_name
 */
ApplicationCreate.prototype['qs_company_name'] = undefined;

/**
 * @member {String} qs_contact_name
 */
ApplicationCreate.prototype['qs_contact_name'] = undefined;

/**
 * @member {String} qs_phone
 */
ApplicationCreate.prototype['qs_phone'] = undefined;

/**
 * @member {String} qs_email
 */
ApplicationCreate.prototype['qs_email'] = undefined;

/**
 * @member {module:models/FundingCalculationInput} funding_calculation_input
 */
ApplicationCreate.prototype['funding_calculation_input'] = undefined;






export default ApplicationCreate;

