/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GuarantorTypeEnum from './GuarantorTypeEnum';
import User from './User';

/**
 * The BorrowerGuarantor model module.
 * @module models/BorrowerGuarantor
 * @version 1.0.0
 */
class BorrowerGuarantor {
    /**
     * Constructs a new <code>BorrowerGuarantor</code>.
     * Serializer for guarantor information
     * @alias module:models/BorrowerGuarantor
     * @param id {Number} 
     * @param createdBy {module:models/User} 
     * @param createdAt {Date} 
     * @param updatedAt {Date} 
     */
    constructor(id, createdBy, createdAt, updatedAt) { 
        
        BorrowerGuarantor.initialize(this, id, createdBy, createdAt, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, createdBy, createdAt, updatedAt) { 
        obj['id'] = id;
        obj['created_by'] = createdBy;
        obj['created_at'] = createdAt;
        obj['updated_at'] = updatedAt;
    }

    /**
     * Constructs a <code>BorrowerGuarantor</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/BorrowerGuarantor} obj Optional instance to populate.
     * @return {module:models/BorrowerGuarantor} The populated <code>BorrowerGuarantor</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BorrowerGuarantor();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('created_by')) {
                obj['created_by'] = ApiClient.convertToType(data['created_by'], User);
            }
            if (data.hasOwnProperty('guarantor_type')) {
                obj['guarantor_type'] = GuarantorTypeEnum.constructFromObject(data['guarantor_type']);
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('date_of_birth')) {
                obj['date_of_birth'] = ApiClient.convertToType(data['date_of_birth'], 'Date');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('company_name')) {
                obj['company_name'] = ApiClient.convertToType(data['company_name'], 'String');
            }
            if (data.hasOwnProperty('company_abn')) {
                obj['company_abn'] = ApiClient.convertToType(data['company_abn'], 'String');
            }
            if (data.hasOwnProperty('company_acn')) {
                obj['company_acn'] = ApiClient.convertToType(data['company_acn'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('borrower')) {
                obj['borrower'] = ApiClient.convertToType(data['borrower'], 'Number');
            }
            if (data.hasOwnProperty('application')) {
                obj['application'] = ApiClient.convertToType(data['application'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BorrowerGuarantor</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BorrowerGuarantor</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BorrowerGuarantor.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `created_by`
        if (data['created_by']) { // data not null
          User.validateJSON(data['created_by']);
        }
        // ensure the json data is a string
        if (data['first_name'] && !(typeof data['first_name'] === 'string' || data['first_name'] instanceof String)) {
            throw new Error("Expected the field `first_name` to be a primitive type in the JSON string but got " + data['first_name']);
        }
        // ensure the json data is a string
        if (data['last_name'] && !(typeof data['last_name'] === 'string' || data['last_name'] instanceof String)) {
            throw new Error("Expected the field `last_name` to be a primitive type in the JSON string but got " + data['last_name']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }
        // ensure the json data is a string
        if (data['company_name'] && !(typeof data['company_name'] === 'string' || data['company_name'] instanceof String)) {
            throw new Error("Expected the field `company_name` to be a primitive type in the JSON string but got " + data['company_name']);
        }
        // ensure the json data is a string
        if (data['company_abn'] && !(typeof data['company_abn'] === 'string' || data['company_abn'] instanceof String)) {
            throw new Error("Expected the field `company_abn` to be a primitive type in the JSON string but got " + data['company_abn']);
        }
        // ensure the json data is a string
        if (data['company_acn'] && !(typeof data['company_acn'] === 'string' || data['company_acn'] instanceof String)) {
            throw new Error("Expected the field `company_acn` to be a primitive type in the JSON string but got " + data['company_acn']);
        }

        return true;
    }


}

BorrowerGuarantor.RequiredProperties = ["id", "created_by", "created_at", "updated_at"];

/**
 * @member {Number} id
 */
BorrowerGuarantor.prototype['id'] = undefined;

/**
 * @member {module:models/User} created_by
 */
BorrowerGuarantor.prototype['created_by'] = undefined;

/**
 * @member {module:models/GuarantorTypeEnum} guarantor_type
 */
BorrowerGuarantor.prototype['guarantor_type'] = undefined;

/**
 * @member {String} first_name
 */
BorrowerGuarantor.prototype['first_name'] = undefined;

/**
 * @member {String} last_name
 */
BorrowerGuarantor.prototype['last_name'] = undefined;

/**
 * @member {Date} date_of_birth
 */
BorrowerGuarantor.prototype['date_of_birth'] = undefined;

/**
 * @member {String} email
 */
BorrowerGuarantor.prototype['email'] = undefined;

/**
 * @member {String} phone
 */
BorrowerGuarantor.prototype['phone'] = undefined;

/**
 * @member {String} address
 */
BorrowerGuarantor.prototype['address'] = undefined;

/**
 * @member {String} company_name
 */
BorrowerGuarantor.prototype['company_name'] = undefined;

/**
 * @member {String} company_abn
 */
BorrowerGuarantor.prototype['company_abn'] = undefined;

/**
 * @member {String} company_acn
 */
BorrowerGuarantor.prototype['company_acn'] = undefined;

/**
 * @member {Date} created_at
 */
BorrowerGuarantor.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
BorrowerGuarantor.prototype['updated_at'] = undefined;

/**
 * @member {Number} borrower
 */
BorrowerGuarantor.prototype['borrower'] = undefined;

/**
 * @member {Number} application
 */
BorrowerGuarantor.prototype['application'] = undefined;






export default BorrowerGuarantor;

