/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Address from './Address';
import Director from './Director';
import FinancialInfo from './FinancialInfo';

/**
 * The CompanyBorrower model module.
 * @module models/CompanyBorrower
 * @version 1.0.0
 */
class CompanyBorrower {
    /**
     * Constructs a new <code>CompanyBorrower</code>.
     * @alias module:models/CompanyBorrower
     * @param id {Number} 
     * @param registeredAddress {module:models/Address} 
     * @param directors {Array.<module:models/Director>} 
     * @param financialInfo {module:models/FinancialInfo} 
     */
    constructor(id, registeredAddress, directors, financialInfo) { 
        
        CompanyBorrower.initialize(this, id, registeredAddress, directors, financialInfo);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, registeredAddress, directors, financialInfo) { 
        obj['id'] = id;
        obj['registered_address'] = registeredAddress;
        obj['directors'] = directors;
        obj['financial_info'] = financialInfo;
    }

    /**
     * Constructs a <code>CompanyBorrower</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/CompanyBorrower} obj Optional instance to populate.
     * @return {module:models/CompanyBorrower} The populated <code>CompanyBorrower</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompanyBorrower();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('company_name')) {
                obj['company_name'] = ApiClient.convertToType(data['company_name'], 'String');
            }
            if (data.hasOwnProperty('company_abn')) {
                obj['company_abn'] = ApiClient.convertToType(data['company_abn'], 'String');
            }
            if (data.hasOwnProperty('company_acn')) {
                obj['company_acn'] = ApiClient.convertToType(data['company_acn'], 'String');
            }
            if (data.hasOwnProperty('registered_address')) {
                obj['registered_address'] = Address.constructFromObject(data['registered_address']);
            }
            if (data.hasOwnProperty('directors')) {
                obj['directors'] = ApiClient.convertToType(data['directors'], [Director]);
            }
            if (data.hasOwnProperty('financial_info')) {
                obj['financial_info'] = FinancialInfo.constructFromObject(data['financial_info']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CompanyBorrower</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CompanyBorrower</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CompanyBorrower.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['company_name'] && !(typeof data['company_name'] === 'string' || data['company_name'] instanceof String)) {
            throw new Error("Expected the field `company_name` to be a primitive type in the JSON string but got " + data['company_name']);
        }
        // ensure the json data is a string
        if (data['company_abn'] && !(typeof data['company_abn'] === 'string' || data['company_abn'] instanceof String)) {
            throw new Error("Expected the field `company_abn` to be a primitive type in the JSON string but got " + data['company_abn']);
        }
        // ensure the json data is a string
        if (data['company_acn'] && !(typeof data['company_acn'] === 'string' || data['company_acn'] instanceof String)) {
            throw new Error("Expected the field `company_acn` to be a primitive type in the JSON string but got " + data['company_acn']);
        }
        // validate the optional field `registered_address`
        if (data['registered_address']) { // data not null
          Address.validateJSON(data['registered_address']);
        }
        if (data['directors']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['directors'])) {
                throw new Error("Expected the field `directors` to be an array in the JSON data but got " + data['directors']);
            }
            // validate the optional field `directors` (array)
            for (const item of data['directors']) {
                Director.validateJSON(item);
            };
        }
        // validate the optional field `financial_info`
        if (data['financial_info']) { // data not null
          FinancialInfo.validateJSON(data['financial_info']);
        }

        return true;
    }


}

CompanyBorrower.RequiredProperties = ["id", "registered_address", "directors", "financial_info"];

/**
 * @member {Number} id
 */
CompanyBorrower.prototype['id'] = undefined;

/**
 * @member {String} company_name
 */
CompanyBorrower.prototype['company_name'] = undefined;

/**
 * @member {String} company_abn
 */
CompanyBorrower.prototype['company_abn'] = undefined;

/**
 * @member {String} company_acn
 */
CompanyBorrower.prototype['company_acn'] = undefined;

/**
 * @member {module:models/Address} registered_address
 */
CompanyBorrower.prototype['registered_address'] = undefined;

/**
 * @member {Array.<module:models/Director>} directors
 */
CompanyBorrower.prototype['directors'] = undefined;

/**
 * @member {module:models/FinancialInfo} financial_info
 */
CompanyBorrower.prototype['financial_info'] = undefined;






export default CompanyBorrower;

