/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class DocumentTypeEnum.
* @enum {}
* @readonly
*/
export default class DocumentTypeEnum {
    
        /**
         * value: "application_form"
         * @const
         */
        "application_form" = "application_form";

    
        /**
         * value: "indicative_letter"
         * @const
         */
        "indicative_letter" = "indicative_letter";

    
        /**
         * value: "formal_approval"
         * @const
         */
        "formal_approval" = "formal_approval";

    
        /**
         * value: "valuation_report"
         * @const
         */
        "valuation_report" = "valuation_report";

    
        /**
         * value: "qs_report"
         * @const
         */
        "qs_report" = "qs_report";

    
        /**
         * value: "id_verification"
         * @const
         */
        "id_verification" = "id_verification";

    
        /**
         * value: "bank_statement"
         * @const
         */
        "bank_statement" = "bank_statement";

    
        /**
         * value: "payslip"
         * @const
         */
        "payslip" = "payslip";

    
        /**
         * value: "tax_return"
         * @const
         */
        "tax_return" = "tax_return";

    
        /**
         * value: "contract"
         * @const
         */
        "contract" = "contract";

    
        /**
         * value: "other"
         * @const
         */
        "other" = "other";

    

    /**
    * Returns a <code>DocumentTypeEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:models/DocumentTypeEnum} The enum <code>DocumentTypeEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

