/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NoteComment model module.
 * @module models/NoteComment
 * @version 1.0.0
 */
class NoteComment {
    /**
     * Constructs a new <code>NoteComment</code>.
     * Serializer for note comments
     * @alias module:models/NoteComment
     * @param id {Number} 
     * @param note {Number} 
     * @param content {String} 
     * @param createdBy {Number} 
     * @param createdByName {String} 
     * @param createdAt {Date} 
     * @param updatedAt {Date} 
     */
    constructor(id, note, content, createdBy, createdByName, createdAt, updatedAt) { 
        
        NoteComment.initialize(this, id, note, content, createdBy, createdByName, createdAt, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, note, content, createdBy, createdByName, createdAt, updatedAt) { 
        obj['id'] = id;
        obj['note'] = note;
        obj['content'] = content;
        obj['created_by'] = createdBy;
        obj['created_by_name'] = createdByName;
        obj['created_at'] = createdAt;
        obj['updated_at'] = updatedAt;
    }

    /**
     * Constructs a <code>NoteComment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/NoteComment} obj Optional instance to populate.
     * @return {module:models/NoteComment} The populated <code>NoteComment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NoteComment();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'Number');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('created_by')) {
                obj['created_by'] = ApiClient.convertToType(data['created_by'], 'Number');
            }
            if (data.hasOwnProperty('created_by_name')) {
                obj['created_by_name'] = ApiClient.convertToType(data['created_by_name'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>NoteComment</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>NoteComment</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of NoteComment.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['content'] && !(typeof data['content'] === 'string' || data['content'] instanceof String)) {
            throw new Error("Expected the field `content` to be a primitive type in the JSON string but got " + data['content']);
        }
        // ensure the json data is a string
        if (data['created_by_name'] && !(typeof data['created_by_name'] === 'string' || data['created_by_name'] instanceof String)) {
            throw new Error("Expected the field `created_by_name` to be a primitive type in the JSON string but got " + data['created_by_name']);
        }

        return true;
    }


}

NoteComment.RequiredProperties = ["id", "note", "content", "created_by", "created_by_name", "created_at", "updated_at"];

/**
 * @member {Number} id
 */
NoteComment.prototype['id'] = undefined;

/**
 * @member {Number} note
 */
NoteComment.prototype['note'] = undefined;

/**
 * @member {String} content
 */
NoteComment.prototype['content'] = undefined;

/**
 * @member {Number} created_by
 */
NoteComment.prototype['created_by'] = undefined;

/**
 * @member {String} created_by_name
 */
NoteComment.prototype['created_by_name'] = undefined;

/**
 * @member {Date} created_at
 */
NoteComment.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
NoteComment.prototype['updated_at'] = undefined;






export default NoteComment;

