/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NoteCommentRequest model module.
 * @module models/NoteCommentRequest
 * @version 1.0.0
 */
class NoteCommentRequest {
    /**
     * Constructs a new <code>NoteCommentRequest</code>.
     * Serializer for note comments
     * @alias module:models/NoteCommentRequest
     * @param note {Number} 
     * @param content {String} 
     */
    constructor(note, content) { 
        
        NoteCommentRequest.initialize(this, note, content);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, note, content) { 
        obj['note'] = note;
        obj['content'] = content;
    }

    /**
     * Constructs a <code>NoteCommentRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/NoteCommentRequest} obj Optional instance to populate.
     * @return {module:models/NoteCommentRequest} The populated <code>NoteCommentRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NoteCommentRequest();

            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'Number');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>NoteCommentRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>NoteCommentRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of NoteCommentRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['content'] && !(typeof data['content'] === 'string' || data['content'] instanceof String)) {
            throw new Error("Expected the field `content` to be a primitive type in the JSON string but got " + data['content']);
        }

        return true;
    }


}

NoteCommentRequest.RequiredProperties = ["note", "content"];

/**
 * @member {Number} note
 */
NoteCommentRequest.prototype['note'] = undefined;

/**
 * @member {String} content
 */
NoteCommentRequest.prototype['content'] = undefined;






export default NoteCommentRequest;

