/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NotificationPreference model module.
 * @module models/NotificationPreference
 * @version 1.0.0
 */
class NotificationPreference {
    /**
     * Constructs a new <code>NotificationPreference</code>.
     * Serializer for NotificationPreference model
     * @alias module:models/NotificationPreference
     * @param id {Number} 
     */
    constructor(id) { 
        
        NotificationPreference.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>NotificationPreference</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/NotificationPreference} obj Optional instance to populate.
     * @return {module:models/NotificationPreference} The populated <code>NotificationPreference</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NotificationPreference();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('application_status_in_app')) {
                obj['application_status_in_app'] = ApiClient.convertToType(data['application_status_in_app'], 'Boolean');
            }
            if (data.hasOwnProperty('repayment_upcoming_in_app')) {
                obj['repayment_upcoming_in_app'] = ApiClient.convertToType(data['repayment_upcoming_in_app'], 'Boolean');
            }
            if (data.hasOwnProperty('repayment_overdue_in_app')) {
                obj['repayment_overdue_in_app'] = ApiClient.convertToType(data['repayment_overdue_in_app'], 'Boolean');
            }
            if (data.hasOwnProperty('note_reminder_in_app')) {
                obj['note_reminder_in_app'] = ApiClient.convertToType(data['note_reminder_in_app'], 'Boolean');
            }
            if (data.hasOwnProperty('document_uploaded_in_app')) {
                obj['document_uploaded_in_app'] = ApiClient.convertToType(data['document_uploaded_in_app'], 'Boolean');
            }
            if (data.hasOwnProperty('signature_required_in_app')) {
                obj['signature_required_in_app'] = ApiClient.convertToType(data['signature_required_in_app'], 'Boolean');
            }
            if (data.hasOwnProperty('system_in_app')) {
                obj['system_in_app'] = ApiClient.convertToType(data['system_in_app'], 'Boolean');
            }
            if (data.hasOwnProperty('application_status_email')) {
                obj['application_status_email'] = ApiClient.convertToType(data['application_status_email'], 'Boolean');
            }
            if (data.hasOwnProperty('repayment_upcoming_email')) {
                obj['repayment_upcoming_email'] = ApiClient.convertToType(data['repayment_upcoming_email'], 'Boolean');
            }
            if (data.hasOwnProperty('repayment_overdue_email')) {
                obj['repayment_overdue_email'] = ApiClient.convertToType(data['repayment_overdue_email'], 'Boolean');
            }
            if (data.hasOwnProperty('note_reminder_email')) {
                obj['note_reminder_email'] = ApiClient.convertToType(data['note_reminder_email'], 'Boolean');
            }
            if (data.hasOwnProperty('document_uploaded_email')) {
                obj['document_uploaded_email'] = ApiClient.convertToType(data['document_uploaded_email'], 'Boolean');
            }
            if (data.hasOwnProperty('signature_required_email')) {
                obj['signature_required_email'] = ApiClient.convertToType(data['signature_required_email'], 'Boolean');
            }
            if (data.hasOwnProperty('system_email')) {
                obj['system_email'] = ApiClient.convertToType(data['system_email'], 'Boolean');
            }
            if (data.hasOwnProperty('daily_digest')) {
                obj['daily_digest'] = ApiClient.convertToType(data['daily_digest'], 'Boolean');
            }
            if (data.hasOwnProperty('weekly_digest')) {
                obj['weekly_digest'] = ApiClient.convertToType(data['weekly_digest'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>NotificationPreference</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>NotificationPreference</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of NotificationPreference.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

NotificationPreference.RequiredProperties = ["id"];

/**
 * @member {Number} id
 */
NotificationPreference.prototype['id'] = undefined;

/**
 * @member {Boolean} application_status_in_app
 */
NotificationPreference.prototype['application_status_in_app'] = undefined;

/**
 * @member {Boolean} repayment_upcoming_in_app
 */
NotificationPreference.prototype['repayment_upcoming_in_app'] = undefined;

/**
 * @member {Boolean} repayment_overdue_in_app
 */
NotificationPreference.prototype['repayment_overdue_in_app'] = undefined;

/**
 * @member {Boolean} note_reminder_in_app
 */
NotificationPreference.prototype['note_reminder_in_app'] = undefined;

/**
 * @member {Boolean} document_uploaded_in_app
 */
NotificationPreference.prototype['document_uploaded_in_app'] = undefined;

/**
 * @member {Boolean} signature_required_in_app
 */
NotificationPreference.prototype['signature_required_in_app'] = undefined;

/**
 * @member {Boolean} system_in_app
 */
NotificationPreference.prototype['system_in_app'] = undefined;

/**
 * @member {Boolean} application_status_email
 */
NotificationPreference.prototype['application_status_email'] = undefined;

/**
 * @member {Boolean} repayment_upcoming_email
 */
NotificationPreference.prototype['repayment_upcoming_email'] = undefined;

/**
 * @member {Boolean} repayment_overdue_email
 */
NotificationPreference.prototype['repayment_overdue_email'] = undefined;

/**
 * @member {Boolean} note_reminder_email
 */
NotificationPreference.prototype['note_reminder_email'] = undefined;

/**
 * @member {Boolean} document_uploaded_email
 */
NotificationPreference.prototype['document_uploaded_email'] = undefined;

/**
 * @member {Boolean} signature_required_email
 */
NotificationPreference.prototype['signature_required_email'] = undefined;

/**
 * @member {Boolean} system_email
 */
NotificationPreference.prototype['system_email'] = undefined;

/**
 * @member {Boolean} daily_digest
 */
NotificationPreference.prototype['daily_digest'] = undefined;

/**
 * @member {Boolean} weekly_digest
 */
NotificationPreference.prototype['weekly_digest'] = undefined;






export default NotificationPreference;

