# Generated by Django 4.2.7 on 2025-04-21 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_user_username_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status_in_app', models.BooleanField(default=True)),
                ('repayment_upcoming_in_app', models.BooleanField(default=True)),
                ('repayment_overdue_in_app', models.BooleanField(default=True)),
                ('note_reminder_in_app', models.BooleanField(default=True)),
                ('document_uploaded_in_app', models.BooleanField(default=True)),
                ('signature_required_in_app', models.BooleanField(default=True)),
                ('system_in_app', models.BooleanField(default=True)),
                ('application_status_email', models.BooleanField(default=True)),
                ('repayment_upcoming_email', models.BooleanField(default=True)),
                ('repayment_overdue_email', models.BooleanField(default=True)),
                ('note_reminder_email', models.BooleanField(default=True)),
                ('document_uploaded_email', models.BooleanField(default=False)),
                ('signature_required_email', models.BooleanField(default=True)),
                ('system_email', models.BooleanField(default=False)),
                ('daily_digest', models.BooleanField(default=False)),
                ('weekly_digest', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
