# Generated by Django 4.2.7 on 2025-05-05 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification_read_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
