# Generated by Django 4.2.20 on 2025-04-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('inquiry', 'Inquiry'), ('application', 'Application'), ('assessment', 'Assessment'), ('approved', 'Approved'), ('settlement', 'Settlement'), ('active', 'Active'), ('closed', 'Closed'), ('declined', 'Declined')], default='inquiry', max_length=20)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_term', models.IntegerField(help_text='Term in months')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('purpose', models.TextField()),
                ('repayment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('fortnightly', 'Fortnightly'), ('weekly', 'Weekly')], default='monthly', max_length=20)),
                ('application_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('construction', 'Construction'), ('refinance', 'Refinance')], max_length=20)),
                ('product_id', models.CharField(blank=True, max_length=50, null=True)),
                ('estimated_settlement_date', models.DateField(blank=True, null=True)),
                ('signed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('signature_date', models.DateField(blank=True, null=True)),
                ('uploaded_pdf_path', models.FileField(blank=True, null=True, upload_to='applications/pdfs/')),
                ('valuer_info', models.JSONField(blank=True, null=True)),
                ('qs_info', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
