# Generated by Django 4.2.20 on 2025-04-21 02:58

import applications.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brokers', '0003_alter_bdm_options_alter_branch_options_and_more'),
        ('borrowers', '0002_borrower_applications_borrower_created_by_and_more'),
        ('applications', '0002_application_bd_application_branch_application_broker_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='application',
            name='qs_info',
        ),
        migrations.RemoveField(
            model_name='application',
            name='valuer_info',
        ),
        migrations.AddField(
            model_name='application',
            name='borrowers',
            field=models.ManyToManyField(related_name='borrower_applications', to='borrowers.borrower'),
        ),
        migrations.AddField(
            model_name='application',
            name='guarantors',
            field=models.ManyToManyField(blank=True, related_name='guaranteed_applications', to='borrowers.guarantor'),
        ),
        migrations.AddField(
            model_name='application',
            name='qs_company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='qs_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='qs_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='qs_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='qs_report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='security_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='security_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='security_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='valuation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='valuation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='valuer_company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='valuer_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='valuer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='valuer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('construction', 'Construction'), ('refinance', 'Refinance'), ('investment', 'Investment'), ('smsf', 'SMSF')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='bd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bdm_applications', to='brokers.bdm'),
        ),
        migrations.AlterField(
            model_name='application',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_applications', to='brokers.branch'),
        ),
        migrations.AlterField(
            model_name='application',
            name='broker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_applications', to='brokers.broker'),
        ),
        migrations.AlterField(
            model_name='application',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='loan_term',
            field=models.PositiveIntegerField(blank=True, help_text='Loan term in months', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='purpose',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='reference_number',
            field=models.CharField(default=applications.models.generate_reference_number, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='repayment_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('inquiry', 'Inquiry'), ('pre_approval', 'Pre-Approval'), ('valuation', 'Valuation'), ('formal_approval', 'Formal Approval'), ('settlement', 'Settlement'), ('funded', 'Funded'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='inquiry', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='uploaded_pdf_path',
            field=models.FileField(blank=True, null=True, upload_to='applications/signed_forms/'),
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('paid', 'Paid'), ('missed', 'Missed'), ('partial', 'Partial Payment')], default='scheduled', max_length=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='repayment_invoices/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_repayments', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('application', 'Application Fee'), ('valuation', 'Valuation Fee'), ('legal', 'Legal Fee'), ('broker', 'Broker Commission'), ('settlement', 'Settlement Fee'), ('other', 'Other Fee')], default='other', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('waived', 'Waived'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_fees', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id', 'Identification'), ('income', 'Income Verification'), ('bank_statement', 'Bank Statement'), ('property', 'Property Document'), ('application', 'Application Form'), ('contract', 'Contract'), ('valuation', 'Valuation Report'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_documents', to='applications.application')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
