# Generated by Django 4.2.7 on 2025-05-01 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_options_remove_application_qs_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='stage_last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
