# Generated by Django 4.2.7 on 2025-05-06 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0006_alter_application_funding_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='additional_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='exit_strategy',
            field=models.CharField(blank=True, choices=[('sale', 'Sale of Property'), ('refinance', 'Refinance'), ('income', 'Income/Cash Flow'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='exit_strategy_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='loan_purpose',
            field=models.CharField(blank=True, choices=[('purchase', 'Purchase'), ('refinance', 'Refinance'), ('construction', 'Construction'), ('equity_release', 'Equity Release'), ('debt_consolidation', 'Debt Consolidation'), ('business_expansion', 'Business Expansion'), ('working_capital', 'Working Capital'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='prior_application',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='prior_application_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SecurityProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('address_street_no', models.CharField(blank=True, max_length=20, null=True)),
                ('address_street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address_suburb', models.CharField(blank=True, max_length=100, null=True)),
                ('address_state', models.CharField(blank=True, max_length=50, null=True)),
                ('address_postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('current_mortgagee', models.CharField(blank=True, max_length=255, null=True)),
                ('first_mortgage', models.CharField(blank=True, max_length=255, null=True)),
                ('second_mortgage', models.CharField(blank=True, max_length=255, null=True)),
                ('current_debt_position', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('property_type', models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('retail', 'Retail'), ('land', 'Land'), ('rural', 'Rural'), ('other', 'Other')], max_length=20, null=True)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('car_spaces', models.PositiveIntegerField(blank=True, null=True)),
                ('building_size', models.DecimalField(blank=True, decimal_places=2, help_text='Size in square meters', max_digits=10, null=True)),
                ('land_size', models.DecimalField(blank=True, decimal_places=2, help_text='Size in square meters', max_digits=10, null=True)),
                ('is_single_story', models.BooleanField(default=True)),
                ('has_garage', models.BooleanField(default=False)),
                ('has_carport', models.BooleanField(default=False)),
                ('has_off_street_parking', models.BooleanField(default=False)),
                ('occupancy', models.CharField(blank=True, choices=[('owner_occupied', 'Owner Occupied'), ('investment', 'Investment Property')], max_length=20, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_properties', to='applications.application')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requirements', to='applications.application')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
