# Generated by Django 4.2.7 on 2025-05-13 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_add_solvency_enquiries'),
        ('applications', '0008_add_solvency_enquiries'),
    ]

    operations = [
    ]
