# Generated by Django 4.2.7 on 2025-05-13 00:40

from django.db import migrations


class Migration(migrations.Migration):
    """
    This migration is intentionally empty because the fields were already added
    in previous migrations (0006_add_solvency_enquiries.py and 0008_add_solvency_enquiries.py).
    We keep this file to maintain migration history and dependencies.
    """

    dependencies = [
        ('applications', '0010_remove_duplicate_solvency_fields'),
    ]

    operations = [
        # No operations needed since the fields already exist in the database
    ]
