# Generated by Django 4.2.7 on 2025-05-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    This migration is now empty because the fields were already added to the database.
    We keep this file to maintain migration history and dependencies.
    """

    dependencies = [
        ('applications', '0011_application_has_been_bankrupt_and_more'),
    ]

    operations = [
        # No operations needed since the fields already exist in the database
    ]
