# Generated by Django 4.2.20 on 2025-04-21 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrowers', '0003_alter_borrower_options_alter_guarantor_options_and_more'),
        ('applications', '0003_alter_application_options_remove_application_qs_info_and_more'),
        ('documents', '0002_document_application_document_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['due_date']},
        ),
        migrations.AlterModelOptions(
            name='ledger',
            options={'ordering': ['-transaction_date'], 'verbose_name_plural': 'ledger entries'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='repayment',
            options={'ordering': ['due_date']},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='ledger',
            old_name='fee',
            new_name='related_fee',
        ),
        migrations.RenameField(
            model_name='ledger',
            old_name='repayment',
            new_name='related_repayment',
        ),
        migrations.RenameField(
            model_name='repayment',
            old_name='payment_date',
            new_name='paid_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='status',
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='status',
        ),
        migrations.AddField(
            model_name='document',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='borrowers.borrower'),
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(blank=True, default='document.pdf', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, default='application/pdf', help_text='MIME type', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='documents.document'),
        ),
        migrations.AddField(
            model_name='fee',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='borrowers.borrower'),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, default='Note', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='overdue_10_day_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repayment',
            name='overdue_3_day_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repayment',
            name='overdue_7_day_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repayment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('application_form', 'Application Form'), ('indicative_letter', 'Indicative Letter'), ('formal_approval', 'Formal Approval'), ('valuation_report', 'Valuation Report'), ('qs_report', 'Quantity Surveyor Report'), ('id_verification', 'ID Verification'), ('bank_statement', 'Bank Statement'), ('payslip', 'Payslip'), ('tax_return', 'Tax Return'), ('contract', 'Contract'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=documents.models.document_upload_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='applications.application'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_type',
            field=models.CharField(choices=[('application', 'Application Fee'), ('valuation', 'Valuation Fee'), ('legal', 'Legal Fee'), ('broker', 'Broker Fee'), ('settlement', 'Settlement Fee'), ('other', 'Other Fee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fee',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.invoice_upload_path),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='applications.application'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='transaction_type',
            field=models.CharField(choices=[('fee_created', 'Fee Created'), ('fee_paid', 'Fee Paid'), ('repayment_scheduled', 'Repayment Scheduled'), ('repayment_received', 'Repayment Received'), ('adjustment', 'Adjustment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='applications.application'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='remind_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='applications.application'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.invoice_upload_path),
        ),
    ]
