# Generated by Django 4.2.7 on 2025-04-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_options_alter_fee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
