/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CrmClientJs);
  }
}(this, function(expect, CrmClientJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CrmClientJs.ApplicationCreateRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApplicationCreateRequest', function() {
    it('should create an instance of ApplicationCreateRequest', function() {
      // uncomment below and update the code to test ApplicationCreateRequest
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be.a(CrmClientJs.ApplicationCreateRequest);
    });

    it('should have the property referenceNumber (base name: "reference_number")', function() {
      // uncomment below and update the code to test the property referenceNumber
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property loanAmount (base name: "loan_amount")', function() {
      // uncomment below and update the code to test the property loanAmount
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property loanTerm (base name: "loan_term")', function() {
      // uncomment below and update the code to test the property loanTerm
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property interestRate (base name: "interest_rate")', function() {
      // uncomment below and update the code to test the property interestRate
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property purpose (base name: "purpose")', function() {
      // uncomment below and update the code to test the property purpose
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property repaymentFrequency (base name: "repayment_frequency")', function() {
      // uncomment below and update the code to test the property repaymentFrequency
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property applicationType (base name: "application_type")', function() {
      // uncomment below and update the code to test the property applicationType
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property productId (base name: "product_id")', function() {
      // uncomment below and update the code to test the property productId
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property estimatedSettlementDate (base name: "estimated_settlement_date")', function() {
      // uncomment below and update the code to test the property estimatedSettlementDate
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property stage (base name: "stage")', function() {
      // uncomment below and update the code to test the property stage
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property borrowers (base name: "borrowers")', function() {
      // uncomment below and update the code to test the property borrowers
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property guarantors (base name: "guarantors")', function() {
      // uncomment below and update the code to test the property guarantors
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property companyBorrowers (base name: "company_borrowers")', function() {
      // uncomment below and update the code to test the property companyBorrowers
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property securityAddress (base name: "security_address")', function() {
      // uncomment below and update the code to test the property securityAddress
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property securityType (base name: "security_type")', function() {
      // uncomment below and update the code to test the property securityType
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property securityValue (base name: "security_value")', function() {
      // uncomment below and update the code to test the property securityValue
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property valuerCompanyName (base name: "valuer_company_name")', function() {
      // uncomment below and update the code to test the property valuerCompanyName
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property valuerContactName (base name: "valuer_contact_name")', function() {
      // uncomment below and update the code to test the property valuerContactName
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property valuerPhone (base name: "valuer_phone")', function() {
      // uncomment below and update the code to test the property valuerPhone
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property valuerEmail (base name: "valuer_email")', function() {
      // uncomment below and update the code to test the property valuerEmail
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property qsCompanyName (base name: "qs_company_name")', function() {
      // uncomment below and update the code to test the property qsCompanyName
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property qsContactName (base name: "qs_contact_name")', function() {
      // uncomment below and update the code to test the property qsContactName
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property qsPhone (base name: "qs_phone")', function() {
      // uncomment below and update the code to test the property qsPhone
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property qsEmail (base name: "qs_email")', function() {
      // uncomment below and update the code to test the property qsEmail
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property fundingCalculationInput (base name: "funding_calculation_input")', function() {
      // uncomment below and update the code to test the property fundingCalculationInput
      //var instance = new CrmClientJs.ApplicationCreateRequest();
      //expect(instance).to.be();
    });

  });

}));
