/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CrmClientJs);
  }
}(this, function(expect, CrmClientJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CrmClientJs.BrokerDetail();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BrokerDetail', function() {
    it('should create an instance of BrokerDetail', function() {
      // uncomment below and update the code to test BrokerDetail
      //var instance = new CrmClientJs.BrokerDetail();
      //expect(instance).to.be.a(CrmClientJs.BrokerDetail);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new CrmClientJs.BrokerDetail();
      //expect(instance).to.be();
    });

    it('should have the property branch (base name: "branch")', function() {
      // uncomment below and update the code to test the property branch
      //var instance = new CrmClientJs.BrokerDetail();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "created_by")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instance = new CrmClientJs.BrokerDetail();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new CrmClientJs.BrokerDetail();
      //expect(instance).to.be();
    });

    it('should have the property company (base name: "company")', function() {
      // uncomment below and update the code to test the property company
      //var instance = new CrmClientJs.BrokerDetail();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new CrmClientJs.BrokerDetail();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instance = new CrmClientJs.BrokerDetail();
      //expect(instance).to.be();
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instance = new CrmClientJs.BrokerDetail();
      //expect(instance).to.be();
    });

    it('should have the property commissionBankName (base name: "commission_bank_name")', function() {
      // uncomment below and update the code to test the property commissionBankName
      //var instance = new CrmClientJs.BrokerDetail();
      //expect(instance).to.be();
    });

    it('should have the property commissionAccountName (base name: "commission_account_name")', function() {
      // uncomment below and update the code to test the property commissionAccountName
      //var instance = new CrmClientJs.BrokerDetail();
      //expect(instance).to.be();
    });

    it('should have the property commissionAccountNumber (base name: "commission_account_number")', function() {
      // uncomment below and update the code to test the property commissionAccountNumber
      //var instance = new CrmClientJs.BrokerDetail();
      //expect(instance).to.be();
    });

    it('should have the property commissionBsb (base name: "commission_bsb")', function() {
      // uncomment below and update the code to test the property commissionBsb
      //var instance = new CrmClientJs.BrokerDetail();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new CrmClientJs.BrokerDetail();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new CrmClientJs.BrokerDetail();
      //expect(instance).to.be();
    });

    it('should have the property user (base name: "user")', function() {
      // uncomment below and update the code to test the property user
      //var instance = new CrmClientJs.BrokerDetail();
      //expect(instance).to.be();
    });

    it('should have the property bdms (base name: "bdms")', function() {
      // uncomment below and update the code to test the property bdms
      //var instance = new CrmClientJs.BrokerDetail();
      //expect(instance).to.be();
    });

  });

}));
