/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CrmClientJs);
  }
}(this, function(expect, CrmClientJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CrmClientJs.Document();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Document', function() {
    it('should create an instance of Document', function() {
      // uncomment below and update the code to test Document
      //var instance = new CrmClientJs.Document();
      //expect(instance).to.be.a(CrmClientJs.Document);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new CrmClientJs.Document();
      //expect(instance).to.be();
    });

    it('should have the property documentTypeDisplay (base name: "document_type_display")', function() {
      // uncomment below and update the code to test the property documentTypeDisplay
      //var instance = new CrmClientJs.Document();
      //expect(instance).to.be();
    });

    it('should have the property createdByName (base name: "created_by_name")', function() {
      // uncomment below and update the code to test the property createdByName
      //var instance = new CrmClientJs.Document();
      //expect(instance).to.be();
    });

    it('should have the property fileUrl (base name: "file_url")', function() {
      // uncomment below and update the code to test the property fileUrl
      //var instance = new CrmClientJs.Document();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new CrmClientJs.Document();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new CrmClientJs.Document();
      //expect(instance).to.be();
    });

    it('should have the property documentType (base name: "document_type")', function() {
      // uncomment below and update the code to test the property documentType
      //var instance = new CrmClientJs.Document();
      //expect(instance).to.be();
    });

    it('should have the property file (base name: "file")', function() {
      // uncomment below and update the code to test the property file
      //var instance = new CrmClientJs.Document();
      //expect(instance).to.be();
    });

    it('should have the property fileName (base name: "file_name")', function() {
      // uncomment below and update the code to test the property fileName
      //var instance = new CrmClientJs.Document();
      //expect(instance).to.be();
    });

    it('should have the property fileSize (base name: "file_size")', function() {
      // uncomment below and update the code to test the property fileSize
      //var instance = new CrmClientJs.Document();
      //expect(instance).to.be();
    });

    it('should have the property fileType (base name: "file_type")', function() {
      // uncomment below and update the code to test the property fileType
      //var instance = new CrmClientJs.Document();
      //expect(instance).to.be();
    });

    it('should have the property version (base name: "version")', function() {
      // uncomment below and update the code to test the property version
      //var instance = new CrmClientJs.Document();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new CrmClientJs.Document();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new CrmClientJs.Document();
      //expect(instance).to.be();
    });

    it('should have the property previousVersion (base name: "previous_version")', function() {
      // uncomment below and update the code to test the property previousVersion
      //var instance = new CrmClientJs.Document();
      //expect(instance).to.be();
    });

    it('should have the property application (base name: "application")', function() {
      // uncomment below and update the code to test the property application
      //var instance = new CrmClientJs.Document();
      //expect(instance).to.be();
    });

    it('should have the property borrower (base name: "borrower")', function() {
      // uncomment below and update the code to test the property borrower
      //var instance = new CrmClientJs.Document();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "created_by")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instance = new CrmClientJs.Document();
      //expect(instance).to.be();
    });

  });

}));
