/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CrmClientJs);
  }
}(this, function(expect, CrmClientJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CrmClientJs.Note();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Note', function() {
    it('should create an instance of Note', function() {
      // uncomment below and update the code to test Note
      //var instance = new CrmClientJs.Note();
      //expect(instance).to.be.a(CrmClientJs.Note);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new CrmClientJs.Note();
      //expect(instance).to.be();
    });

    it('should have the property createdByName (base name: "created_by_name")', function() {
      // uncomment below and update the code to test the property createdByName
      //var instance = new CrmClientJs.Note();
      //expect(instance).to.be();
    });

    it('should have the property assignedToName (base name: "assigned_to_name")', function() {
      // uncomment below and update the code to test the property assignedToName
      //var instance = new CrmClientJs.Note();
      //expect(instance).to.be();
    });

    it('should have the property comments (base name: "comments")', function() {
      // uncomment below and update the code to test the property comments
      //var instance = new CrmClientJs.Note();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new CrmClientJs.Note();
      //expect(instance).to.be();
    });

    it('should have the property content (base name: "content")', function() {
      // uncomment below and update the code to test the property content
      //var instance = new CrmClientJs.Note();
      //expect(instance).to.be();
    });

    it('should have the property remindDate (base name: "remind_date")', function() {
      // uncomment below and update the code to test the property remindDate
      //var instance = new CrmClientJs.Note();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new CrmClientJs.Note();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new CrmClientJs.Note();
      //expect(instance).to.be();
    });

    it('should have the property application (base name: "application")', function() {
      // uncomment below and update the code to test the property application
      //var instance = new CrmClientJs.Note();
      //expect(instance).to.be();
    });

    it('should have the property borrower (base name: "borrower")', function() {
      // uncomment below and update the code to test the property borrower
      //var instance = new CrmClientJs.Note();
      //expect(instance).to.be();
    });

    it('should have the property assignedTo (base name: "assigned_to")', function() {
      // uncomment below and update the code to test the property assignedTo
      //var instance = new CrmClientJs.Note();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "created_by")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instance = new CrmClientJs.Note();
      //expect(instance).to.be();
    });

  });

}));
