/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CrmClientJs);
  }
}(this, function(expect, CrmClientJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CrmClientJs.Reminder();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Reminder', function() {
    it('should create an instance of Reminder', function() {
      // uncomment below and update the code to test Reminder
      //var instance = new CrmClientJs.Reminder();
      //expect(instance).to.be.a(CrmClientJs.Reminder);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new CrmClientJs.Reminder();
      //expect(instance).to.be();
    });

    it('should have the property recipientType (base name: "recipient_type")', function() {
      // uncomment below and update the code to test the property recipientType
      //var instance = new CrmClientJs.Reminder();
      //expect(instance).to.be();
    });

    it('should have the property recipientEmail (base name: "recipient_email")', function() {
      // uncomment below and update the code to test the property recipientEmail
      //var instance = new CrmClientJs.Reminder();
      //expect(instance).to.be();
    });

    it('should have the property sendDatetime (base name: "send_datetime")', function() {
      // uncomment below and update the code to test the property sendDatetime
      //var instance = new CrmClientJs.Reminder();
      //expect(instance).to.be();
    });

    it('should have the property emailBody (base name: "email_body")', function() {
      // uncomment below and update the code to test the property emailBody
      //var instance = new CrmClientJs.Reminder();
      //expect(instance).to.be();
    });

    it('should have the property subject (base name: "subject")', function() {
      // uncomment below and update the code to test the property subject
      //var instance = new CrmClientJs.Reminder();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "created_by")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instance = new CrmClientJs.Reminder();
      //expect(instance).to.be();
    });

    it('should have the property createdByName (base name: "created_by_name")', function() {
      // uncomment below and update the code to test the property createdByName
      //var instance = new CrmClientJs.Reminder();
      //expect(instance).to.be();
    });

    it('should have the property sendAsUser (base name: "send_as_user")', function() {
      // uncomment below and update the code to test the property sendAsUser
      //var instance = new CrmClientJs.Reminder();
      //expect(instance).to.be();
    });

    it('should have the property sendAsUserEmail (base name: "send_as_user_email")', function() {
      // uncomment below and update the code to test the property sendAsUserEmail
      //var instance = new CrmClientJs.Reminder();
      //expect(instance).to.be();
    });

    it('should have the property replyToUser (base name: "reply_to_user")', function() {
      // uncomment below and update the code to test the property replyToUser
      //var instance = new CrmClientJs.Reminder();
      //expect(instance).to.be();
    });

    it('should have the property replyToUserEmail (base name: "reply_to_user_email")', function() {
      // uncomment below and update the code to test the property replyToUserEmail
      //var instance = new CrmClientJs.Reminder();
      //expect(instance).to.be();
    });

    it('should have the property isSent (base name: "is_sent")', function() {
      // uncomment below and update the code to test the property isSent
      //var instance = new CrmClientJs.Reminder();
      //expect(instance).to.be();
    });

    it('should have the property sentAt (base name: "sent_at")', function() {
      // uncomment below and update the code to test the property sentAt
      //var instance = new CrmClientJs.Reminder();
      //expect(instance).to.be();
    });

    it('should have the property errorMessage (base name: "error_message")', function() {
      // uncomment below and update the code to test the property errorMessage
      //var instance = new CrmClientJs.Reminder();
      //expect(instance).to.be();
    });

    it('should have the property relatedApplication (base name: "related_application")', function() {
      // uncomment below and update the code to test the property relatedApplication
      //var instance = new CrmClientJs.Reminder();
      //expect(instance).to.be();
    });

    it('should have the property relatedBorrower (base name: "related_borrower")', function() {
      // uncomment below and update the code to test the property relatedBorrower
      //var instance = new CrmClientJs.Reminder();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new CrmClientJs.Reminder();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new CrmClientJs.Reminder();
      //expect(instance).to.be();
    });

  });

}));
