# Generated by Django 4.2.7 on 2025-04-20 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0002_application_bd_application_branch_application_broker_and_more'),
        ('borrowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='applications',
            field=models.ManyToManyField(related_name='borrowers', to='applications.application'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_borrowers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrower',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrower_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='applications.application'),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='borrowers.borrower'),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_guarantors', to=settings.AUTH_USER_MODEL),
        ),
    ]
