# Generated by Django 4.2.20 on 2025-04-21 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0003_alter_application_options_remove_application_qs_info_and_more'),
        ('borrowers', '0002_borrower_applications_borrower_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrower',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='guarantor',
            options={'ordering': ['guarantor_type', 'last_name', 'first_name', 'company_name']},
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='applications',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='bank_account_info',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='employment_info',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='income',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='liabilities',
        ),
        migrations.RemoveField(
            model_name='guarantor',
            name='company_registration_number',
        ),
        migrations.RemoveField(
            model_name='guarantor',
            name='financial_info',
        ),
        migrations.AddField(
            model_name='borrower',
            name='annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='bank_bsb',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='company_abn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='company_acn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='company_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='employer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='employer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='employment_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in months', null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('casual', 'Casual'), ('self_employed', 'Self Employed'), ('contractor', 'Contractor'), ('unemployed', 'Unemployed'), ('retired', 'Retired')], default='full_time', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrower',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='monthly_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='notes_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='other_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='company_abn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='company_acn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('de_facto', 'De Facto'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='residency_status',
            field=models.CharField(blank=True, choices=[('citizen', 'Citizen'), ('permanent_resident', 'Permanent Resident'), ('temporary_resident', 'Temporary Resident'), ('foreign_investor', 'Foreign Investor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='residential_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Tax File Number or equivalent', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_guarantors', to='applications.application'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower_guarantors', to='borrowers.borrower'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liability_type', models.CharField(choices=[('mortgage', 'Mortgage'), ('personal_loan', 'Personal Loan'), ('car_loan', 'Car Loan'), ('credit_card', 'Credit Card'), ('tax_debt', 'Tax Debt'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lender', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='borrowers.borrower')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('property', 'Property'), ('vehicle', 'Vehicle'), ('savings', 'Savings'), ('investment', 'Investment'), ('superannuation', 'Superannuation'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('address', models.TextField(blank=True, help_text='For property assets', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='borrowers.borrower')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
