# Generated by Django 4.2.7 on 2025-05-06 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrowers', '0003_alter_borrower_options_alter_guarantor_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guarantor',
            old_name='phone',
            new_name='address_street_no',
        ),
        migrations.AddField(
            model_name='asset',
            name='amount_owing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='borrowers.guarantor'),
        ),
        migrations.AddField(
            model_name='asset',
            name='to_be_refinanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrower',
            name='annual_company_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='industry_type',
            field=models.CharField(blank=True, choices=[('agriculture', 'Agriculture'), ('mining', 'Mining'), ('manufacturing', 'Manufacturing'), ('construction', 'Construction'), ('retail', 'Retail'), ('transport', 'Transport'), ('hospitality', 'Hospitality'), ('finance', 'Finance'), ('real_estate', 'Real Estate'), ('professional', 'Professional Services'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('arts', 'Arts and Recreation'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='is_smsf_trustee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrower',
            name='is_trustee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrower',
            name='registered_address_postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='registered_address_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='registered_address_street_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='registered_address_street_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='registered_address_suburb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='registered_address_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='trustee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='address_postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='address_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='address_street_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='address_suburb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='address_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='drivers_licence_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='employer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('casual', 'Casual/Temp'), ('contract', 'Contract')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='home_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='title',
            field=models.CharField(blank=True, choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('ms', 'Ms'), ('miss', 'Miss'), ('dr', 'Dr'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='liability',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='borrowers.guarantor'),
        ),
        migrations.AddField(
            model_name='liability',
            name='to_be_refinanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('property', 'Property'), ('vehicle', 'Vehicle'), ('savings', 'Savings'), ('investment', 'Investment'), ('shares', 'Shares'), ('superannuation', 'Superannuation'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='borrowers.borrower'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='borrowers.borrower'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='liability_type',
            field=models.CharField(choices=[('mortgage', 'Mortgage'), ('personal_loan', 'Personal Loan'), ('car_loan', 'Car Loan'), ('credit_card', 'Credit Card'), ('tax_debt', 'Tax Debt'), ('other_creditor', 'Other Creditor'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roles', models.CharField(help_text='Comma-separated list of roles', max_length=255)),
                ('director_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='borrowers.borrower')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
