# Generated by Django 4.0.10 on 2025-04-28 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0002_guarantor_relationship_to_borrower'),
        ('borrowers', '0003_alter_borrower_options_alter_guarantor_options_and_more'),
    ]

    operations = [
    ]
