/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CrmClientJs);
  }
}(this, function(expect, CrmClientJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CrmClientJs.RepaymentComplianceReport();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RepaymentComplianceReport', function() {
    it('should create an instance of RepaymentComplianceReport', function() {
      // uncomment below and update the code to test RepaymentComplianceReport
      //var instance = new CrmClientJs.RepaymentComplianceReport();
      //expect(instance).to.be.a(CrmClientJs.RepaymentComplianceReport);
    });

    it('should have the property totalRepayments (base name: "total_repayments")', function() {
      // uncomment below and update the code to test the property totalRepayments
      //var instance = new CrmClientJs.RepaymentComplianceReport();
      //expect(instance).to.be();
    });

    it('should have the property paidOnTime (base name: "paid_on_time")', function() {
      // uncomment below and update the code to test the property paidOnTime
      //var instance = new CrmClientJs.RepaymentComplianceReport();
      //expect(instance).to.be();
    });

    it('should have the property paidLate (base name: "paid_late")', function() {
      // uncomment below and update the code to test the property paidLate
      //var instance = new CrmClientJs.RepaymentComplianceReport();
      //expect(instance).to.be();
    });

    it('should have the property missed (base name: "missed")', function() {
      // uncomment below and update the code to test the property missed
      //var instance = new CrmClientJs.RepaymentComplianceReport();
      //expect(instance).to.be();
    });

    it('should have the property complianceRate (base name: "compliance_rate")', function() {
      // uncomment below and update the code to test the property complianceRate
      //var instance = new CrmClientJs.RepaymentComplianceReport();
      //expect(instance).to.be();
    });

    it('should have the property averageDaysLate (base name: "average_days_late")', function() {
      // uncomment below and update the code to test the property averageDaysLate
      //var instance = new CrmClientJs.RepaymentComplianceReport();
      //expect(instance).to.be();
    });

    it('should have the property totalAmountDue (base name: "total_amount_due")', function() {
      // uncomment below and update the code to test the property totalAmountDue
      //var instance = new CrmClientJs.RepaymentComplianceReport();
      //expect(instance).to.be();
    });

    it('should have the property totalAmountPaid (base name: "total_amount_paid")', function() {
      // uncomment below and update the code to test the property totalAmountPaid
      //var instance = new CrmClientJs.RepaymentComplianceReport();
      //expect(instance).to.be();
    });

    it('should have the property paymentRate (base name: "payment_rate")', function() {
      // uncomment below and update the code to test the property paymentRate
      //var instance = new CrmClientJs.RepaymentComplianceReport();
      //expect(instance).to.be();
    });

    it('should have the property monthlyBreakdown (base name: "monthly_breakdown")', function() {
      // uncomment below and update the code to test the property monthlyBreakdown
      //var instance = new CrmClientJs.RepaymentComplianceReport();
      //expect(instance).to.be();
    });

  });

}));
