/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApplicationTypeEnum from './ApplicationTypeEnum';
import BlankEnum from './BlankEnum';

/**
 * The ApplicationCreateApplicationType model module.
 * @module models/ApplicationCreateApplicationType
 * @version 1.0.0
 */
class ApplicationCreateApplicationType {
    /**
     * Constructs a new <code>ApplicationCreateApplicationType</code>.
     * @alias module:models/ApplicationCreateApplicationType
     * @param {(module:models/ApplicationTypeEnum|module:models/BlankEnum)} instance The actual instance to initialize ApplicationCreateApplicationType.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "ApplicationTypeEnum") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                ApplicationTypeEnum.validateJSON(instance); // throw an exception if no match
                // create ApplicationTypeEnum from JS object
                this.actualInstance = ApplicationTypeEnum.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into ApplicationTypeEnum
            errorMessages.push("Failed to construct ApplicationTypeEnum: " + err)
        }

        try {
            if (typeof instance === "BlankEnum") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                BlankEnum.validateJSON(instance); // throw an exception if no match
                // create BlankEnum from JS object
                this.actualInstance = BlankEnum.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into BlankEnum
            errorMessages.push("Failed to construct BlankEnum: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `ApplicationCreateApplicationType` with oneOf schemas ApplicationTypeEnum, BlankEnum. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `ApplicationCreateApplicationType` with oneOf schemas ApplicationTypeEnum, BlankEnum. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>ApplicationCreateApplicationType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/ApplicationCreateApplicationType} obj Optional instance to populate.
     * @return {module:models/ApplicationCreateApplicationType} The populated <code>ApplicationCreateApplicationType</code> instance.
     */
    static constructFromObject(data, obj) {
        return new ApplicationCreateApplicationType(data);
    }

    /**
     * Gets the actual instance, which can be <code>ApplicationTypeEnum</code>, <code>BlankEnum</code>.
     * @return {(module:models/ApplicationTypeEnum|module:models/BlankEnum)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>ApplicationTypeEnum</code>, <code>BlankEnum</code>.
     * @param {(module:models/ApplicationTypeEnum|module:models/BlankEnum)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = ApplicationCreateApplicationType.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of ApplicationCreateApplicationType from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:models/ApplicationCreateApplicationType} An instance of ApplicationCreateApplicationType.
     */
    static fromJSON = function(json_string){
        return ApplicationCreateApplicationType.constructFromObject(JSON.parse(json_string));
    }
}


ApplicationCreateApplicationType.OneOf = ["ApplicationTypeEnum", "BlankEnum"];

export default ApplicationCreateApplicationType;

