/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Branch from './Branch';
import User from './User';

/**
 * The BDM model module.
 * @module models/BDM
 * @version 1.0.0
 */
class BDM {
    /**
     * Constructs a new <code>BDM</code>.
     * Serializer for BDM information
     * @alias module:models/BDM
     * @param id {Number} 
     * @param branch {module:models/Branch} 
     * @param createdBy {module:models/User} 
     * @param name {String} 
     * @param createdAt {Date} 
     * @param updatedAt {Date} 
     */
    constructor(id, branch, createdBy, name, createdAt, updatedAt) { 
        
        BDM.initialize(this, id, branch, createdBy, name, createdAt, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, branch, createdBy, name, createdAt, updatedAt) { 
        obj['id'] = id;
        obj['branch'] = branch;
        obj['created_by'] = createdBy;
        obj['name'] = name;
        obj['created_at'] = createdAt;
        obj['updated_at'] = updatedAt;
    }

    /**
     * Constructs a <code>BDM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/BDM} obj Optional instance to populate.
     * @return {module:models/BDM} The populated <code>BDM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BDM();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('branch')) {
                obj['branch'] = ApiClient.convertToType(data['branch'], Branch);
            }
            if (data.hasOwnProperty('created_by')) {
                obj['created_by'] = ApiClient.convertToType(data['created_by'], User);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BDM</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BDM</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BDM.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `branch`
        if (data['branch']) { // data not null
          Branch.validateJSON(data['branch']);
        }
        // validate the optional field `created_by`
        if (data['created_by']) { // data not null
          User.validateJSON(data['created_by']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }

        return true;
    }


}

BDM.RequiredProperties = ["id", "branch", "created_by", "name", "created_at", "updated_at"];

/**
 * @member {Number} id
 */
BDM.prototype['id'] = undefined;

/**
 * @member {module:models/Branch} branch
 */
BDM.prototype['branch'] = undefined;

/**
 * @member {module:models/User} created_by
 */
BDM.prototype['created_by'] = undefined;

/**
 * @member {String} name
 */
BDM.prototype['name'] = undefined;

/**
 * @member {String} email
 */
BDM.prototype['email'] = undefined;

/**
 * @member {String} phone
 */
BDM.prototype['phone'] = undefined;

/**
 * @member {Date} created_at
 */
BDM.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
BDM.prototype['updated_at'] = undefined;

/**
 * @member {Number} user
 */
BDM.prototype['user'] = undefined;






export default BDM;

