/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TokenRefreshRequest model module.
 * @module models/TokenRefreshRequest
 * @version 1.0.0
 */
class TokenRefreshRequest {
    /**
     * Constructs a new <code>TokenRefreshRequest</code>.
     * @alias module:models/TokenRefreshRequest
     * @param refresh {String} 
     */
    constructor(refresh) { 
        
        TokenRefreshRequest.initialize(this, refresh);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, refresh) { 
        obj['refresh'] = refresh;
    }

    /**
     * Constructs a <code>TokenRefreshRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/TokenRefreshRequest} obj Optional instance to populate.
     * @return {module:models/TokenRefreshRequest} The populated <code>TokenRefreshRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TokenRefreshRequest();

            if (data.hasOwnProperty('refresh')) {
                obj['refresh'] = ApiClient.convertToType(data['refresh'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TokenRefreshRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TokenRefreshRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TokenRefreshRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['refresh'] && !(typeof data['refresh'] === 'string' || data['refresh'] instanceof String)) {
            throw new Error("Expected the field `refresh` to be a primitive type in the JSON string but got " + data['refresh']);
        }

        return true;
    }


}

TokenRefreshRequest.RequiredProperties = ["refresh"];

/**
 * @member {String} refresh
 */
TokenRefreshRequest.prototype['refresh'] = undefined;






export default TokenRefreshRequest;

