# Generated by Django 4.2.7 on 2025-05-01 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrowers', '0003_alter_borrower_options_alter_guarantor_options_and_more'),
        ('applications', '0004_application_stage_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('client', 'Client'), ('bdm', 'Business Development Manager'), ('broker', 'Broker'), ('custom', 'Custom Email')], max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('send_datetime', models.DateTimeField()),
                ('email_body', models.TextField()),
                ('subject', models.CharField(max_length=255)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reminders', to=settings.AUTH_USER_MODEL)),
                ('related_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='applications.application')),
                ('related_borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='borrowers.borrower')),
                ('reply_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_to_reminders', to=settings.AUTH_USER_MODEL)),
                ('send_as_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_as_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['send_datetime'],
            },
        ),
    ]
