/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StageEnum from './StageEnum';

/**
 * The ApplicationStageUpdate model module.
 * @module models/ApplicationStageUpdate
 * @version 1.0.0
 */
class ApplicationStageUpdate {
    /**
     * Constructs a new <code>ApplicationStageUpdate</code>.
     * @alias module:models/ApplicationStageUpdate
     * @param stage {module:models/StageEnum} 
     */
    constructor(stage) { 
        
        ApplicationStageUpdate.initialize(this, stage);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, stage) { 
        obj['stage'] = stage;
    }

    /**
     * Constructs a <code>ApplicationStageUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/ApplicationStageUpdate} obj Optional instance to populate.
     * @return {module:models/ApplicationStageUpdate} The populated <code>ApplicationStageUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplicationStageUpdate();

            if (data.hasOwnProperty('stage')) {
                obj['stage'] = StageEnum.constructFromObject(data['stage']);
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApplicationStageUpdate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApplicationStageUpdate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApplicationStageUpdate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['notes'] && !(typeof data['notes'] === 'string' || data['notes'] instanceof String)) {
            throw new Error("Expected the field `notes` to be a primitive type in the JSON string but got " + data['notes']);
        }

        return true;
    }


}

ApplicationStageUpdate.RequiredProperties = ["stage"];

/**
 * @member {module:models/StageEnum} stage
 */
ApplicationStageUpdate.prototype['stage'] = undefined;

/**
 * @member {String} notes
 */
ApplicationStageUpdate.prototype['notes'] = undefined;






export default ApplicationStageUpdate;

