/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GuarantorTypeEnum from './GuarantorTypeEnum';

/**
 * The GuarantorRequest model module.
 * @module models/GuarantorRequest
 * @version 1.0.0
 */
class GuarantorRequest {
    /**
     * Constructs a new <code>GuarantorRequest</code>.
     * @alias module:models/GuarantorRequest
     */
    constructor() { 
        
        GuarantorRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GuarantorRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/GuarantorRequest} obj Optional instance to populate.
     * @return {module:models/GuarantorRequest} The populated <code>GuarantorRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GuarantorRequest();

            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('date_of_birth')) {
                obj['date_of_birth'] = ApiClient.convertToType(data['date_of_birth'], 'Date');
            }
            if (data.hasOwnProperty('guarantor_type')) {
                obj['guarantor_type'] = GuarantorTypeEnum.constructFromObject(data['guarantor_type']);
            }
            if (data.hasOwnProperty('borrower')) {
                obj['borrower'] = ApiClient.convertToType(data['borrower'], 'Number');
            }
            if (data.hasOwnProperty('application')) {
                obj['application'] = ApiClient.convertToType(data['application'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GuarantorRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GuarantorRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['first_name'] && !(typeof data['first_name'] === 'string' || data['first_name'] instanceof String)) {
            throw new Error("Expected the field `first_name` to be a primitive type in the JSON string but got " + data['first_name']);
        }
        // ensure the json data is a string
        if (data['last_name'] && !(typeof data['last_name'] === 'string' || data['last_name'] instanceof String)) {
            throw new Error("Expected the field `last_name` to be a primitive type in the JSON string but got " + data['last_name']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }

        return true;
    }


}



/**
 * @member {String} first_name
 */
GuarantorRequest.prototype['first_name'] = undefined;

/**
 * @member {String} last_name
 */
GuarantorRequest.prototype['last_name'] = undefined;

/**
 * @member {String} email
 */
GuarantorRequest.prototype['email'] = undefined;

/**
 * @member {String} phone
 */
GuarantorRequest.prototype['phone'] = undefined;

/**
 * @member {Date} date_of_birth
 */
GuarantorRequest.prototype['date_of_birth'] = undefined;

/**
 * @member {module:models/GuarantorTypeEnum} guarantor_type
 */
GuarantorRequest.prototype['guarantor_type'] = undefined;

/**
 * @member {Number} borrower
 */
GuarantorRequest.prototype['borrower'] = undefined;

/**
 * @member {Number} application
 */
GuarantorRequest.prototype['application'] = undefined;






export default GuarantorRequest;

