/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LoanExtensionRequest model module.
 * @module models/LoanExtensionRequest
 * @version 1.0.0
 */
class LoanExtensionRequest {
    /**
     * Constructs a new <code>LoanExtensionRequest</code>.
     * Serializer for extending a loan with new terms
     * @alias module:models/LoanExtensionRequest
     * @param newRate {Number} 
     * @param newLoanAmount {Number} 
     * @param newRepayment {Number} 
     */
    constructor(newRate, newLoanAmount, newRepayment) { 
        
        LoanExtensionRequest.initialize(this, newRate, newLoanAmount, newRepayment);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, newRate, newLoanAmount, newRepayment) { 
        obj['new_rate'] = newRate;
        obj['new_loan_amount'] = newLoanAmount;
        obj['new_repayment'] = newRepayment;
    }

    /**
     * Constructs a <code>LoanExtensionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/LoanExtensionRequest} obj Optional instance to populate.
     * @return {module:models/LoanExtensionRequest} The populated <code>LoanExtensionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoanExtensionRequest();

            if (data.hasOwnProperty('new_rate')) {
                obj['new_rate'] = ApiClient.convertToType(data['new_rate'], 'Number');
            }
            if (data.hasOwnProperty('new_loan_amount')) {
                obj['new_loan_amount'] = ApiClient.convertToType(data['new_loan_amount'], 'Number');
            }
            if (data.hasOwnProperty('new_repayment')) {
                obj['new_repayment'] = ApiClient.convertToType(data['new_repayment'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LoanExtensionRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LoanExtensionRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of LoanExtensionRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['new_rate'] && !(typeof data['new_rate'] === 'string' || data['new_rate'] instanceof String)) {
            throw new Error("Expected the field `new_rate` to be a primitive type in the JSON string but got " + data['new_rate']);
        }
        // ensure the json data is a string
        if (data['new_loan_amount'] && !(typeof data['new_loan_amount'] === 'string' || data['new_loan_amount'] instanceof String)) {
            throw new Error("Expected the field `new_loan_amount` to be a primitive type in the JSON string but got " + data['new_loan_amount']);
        }
        // ensure the json data is a string
        if (data['new_repayment'] && !(typeof data['new_repayment'] === 'string' || data['new_repayment'] instanceof String)) {
            throw new Error("Expected the field `new_repayment` to be a primitive type in the JSON string but got " + data['new_repayment']);
        }

        return true;
    }


}

LoanExtensionRequest.RequiredProperties = ["new_rate", "new_loan_amount", "new_repayment"];

/**
 * @member {Number} new_rate
 */
LoanExtensionRequest.prototype['new_rate'] = undefined;

/**
 * @member {Number} new_loan_amount
 */
LoanExtensionRequest.prototype['new_loan_amount'] = undefined;

/**
 * @member {Number} new_repayment
 */
LoanExtensionRequest.prototype['new_repayment'] = undefined;






export default LoanExtensionRequest;

