/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PatchedBrokerDetailRequest model module.
 * @module models/PatchedBrokerDetailRequest
 * @version 1.0.0
 */
class PatchedBrokerDetailRequest {
    /**
     * Constructs a new <code>PatchedBrokerDetailRequest</code>.
     * Serializer for detailed broker information
     * @alias module:models/PatchedBrokerDetailRequest
     */
    constructor() { 
        
        PatchedBrokerDetailRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PatchedBrokerDetailRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/PatchedBrokerDetailRequest} obj Optional instance to populate.
     * @return {module:models/PatchedBrokerDetailRequest} The populated <code>PatchedBrokerDetailRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PatchedBrokerDetailRequest();

            if (data.hasOwnProperty('branch_id')) {
                obj['branch_id'] = ApiClient.convertToType(data['branch_id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('company')) {
                obj['company'] = ApiClient.convertToType(data['company'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('commission_bank_name')) {
                obj['commission_bank_name'] = ApiClient.convertToType(data['commission_bank_name'], 'String');
            }
            if (data.hasOwnProperty('commission_account_name')) {
                obj['commission_account_name'] = ApiClient.convertToType(data['commission_account_name'], 'String');
            }
            if (data.hasOwnProperty('commission_account_number')) {
                obj['commission_account_number'] = ApiClient.convertToType(data['commission_account_number'], 'String');
            }
            if (data.hasOwnProperty('commission_bsb')) {
                obj['commission_bsb'] = ApiClient.convertToType(data['commission_bsb'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'Number');
            }
            if (data.hasOwnProperty('bdms')) {
                obj['bdms'] = ApiClient.convertToType(data['bdms'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PatchedBrokerDetailRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PatchedBrokerDetailRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['company'] && !(typeof data['company'] === 'string' || data['company'] instanceof String)) {
            throw new Error("Expected the field `company` to be a primitive type in the JSON string but got " + data['company']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }
        // ensure the json data is a string
        if (data['commission_bank_name'] && !(typeof data['commission_bank_name'] === 'string' || data['commission_bank_name'] instanceof String)) {
            throw new Error("Expected the field `commission_bank_name` to be a primitive type in the JSON string but got " + data['commission_bank_name']);
        }
        // ensure the json data is a string
        if (data['commission_account_name'] && !(typeof data['commission_account_name'] === 'string' || data['commission_account_name'] instanceof String)) {
            throw new Error("Expected the field `commission_account_name` to be a primitive type in the JSON string but got " + data['commission_account_name']);
        }
        // ensure the json data is a string
        if (data['commission_account_number'] && !(typeof data['commission_account_number'] === 'string' || data['commission_account_number'] instanceof String)) {
            throw new Error("Expected the field `commission_account_number` to be a primitive type in the JSON string but got " + data['commission_account_number']);
        }
        // ensure the json data is a string
        if (data['commission_bsb'] && !(typeof data['commission_bsb'] === 'string' || data['commission_bsb'] instanceof String)) {
            throw new Error("Expected the field `commission_bsb` to be a primitive type in the JSON string but got " + data['commission_bsb']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['bdms'])) {
            throw new Error("Expected the field `bdms` to be an array in the JSON data but got " + data['bdms']);
        }

        return true;
    }


}



/**
 * @member {Number} branch_id
 */
PatchedBrokerDetailRequest.prototype['branch_id'] = undefined;

/**
 * @member {String} name
 */
PatchedBrokerDetailRequest.prototype['name'] = undefined;

/**
 * @member {String} company
 */
PatchedBrokerDetailRequest.prototype['company'] = undefined;

/**
 * @member {String} email
 */
PatchedBrokerDetailRequest.prototype['email'] = undefined;

/**
 * @member {String} phone
 */
PatchedBrokerDetailRequest.prototype['phone'] = undefined;

/**
 * @member {String} address
 */
PatchedBrokerDetailRequest.prototype['address'] = undefined;

/**
 * @member {String} commission_bank_name
 */
PatchedBrokerDetailRequest.prototype['commission_bank_name'] = undefined;

/**
 * @member {String} commission_account_name
 */
PatchedBrokerDetailRequest.prototype['commission_account_name'] = undefined;

/**
 * @member {String} commission_account_number
 */
PatchedBrokerDetailRequest.prototype['commission_account_number'] = undefined;

/**
 * @member {String} commission_bsb
 */
PatchedBrokerDetailRequest.prototype['commission_bsb'] = undefined;

/**
 * @member {Number} user
 */
PatchedBrokerDetailRequest.prototype['user'] = undefined;

/**
 * @member {Array.<Number>} bdms
 */
PatchedBrokerDetailRequest.prototype['bdms'] = undefined;






export default PatchedBrokerDetailRequest;

