/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RecipientTypeEnum from './RecipientTypeEnum';

/**
 * The ReminderRequest model module.
 * @module models/ReminderRequest
 * @version 1.0.0
 */
class ReminderRequest {
    /**
     * Constructs a new <code>ReminderRequest</code>.
     * Serializer for reminders
     * @alias module:models/ReminderRequest
     * @param recipientType {module:models/RecipientTypeEnum} 
     * @param recipientEmail {String} 
     * @param sendDatetime {Date} 
     * @param emailBody {String} 
     * @param subject {String} 
     */
    constructor(recipientType, recipientEmail, sendDatetime, emailBody, subject) { 
        
        ReminderRequest.initialize(this, recipientType, recipientEmail, sendDatetime, emailBody, subject);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, recipientType, recipientEmail, sendDatetime, emailBody, subject) { 
        obj['recipient_type'] = recipientType;
        obj['recipient_email'] = recipientEmail;
        obj['send_datetime'] = sendDatetime;
        obj['email_body'] = emailBody;
        obj['subject'] = subject;
    }

    /**
     * Constructs a <code>ReminderRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/ReminderRequest} obj Optional instance to populate.
     * @return {module:models/ReminderRequest} The populated <code>ReminderRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReminderRequest();

            if (data.hasOwnProperty('recipient_type')) {
                obj['recipient_type'] = RecipientTypeEnum.constructFromObject(data['recipient_type']);
            }
            if (data.hasOwnProperty('recipient_email')) {
                obj['recipient_email'] = ApiClient.convertToType(data['recipient_email'], 'String');
            }
            if (data.hasOwnProperty('send_datetime')) {
                obj['send_datetime'] = ApiClient.convertToType(data['send_datetime'], 'Date');
            }
            if (data.hasOwnProperty('email_body')) {
                obj['email_body'] = ApiClient.convertToType(data['email_body'], 'String');
            }
            if (data.hasOwnProperty('subject')) {
                obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
            }
            if (data.hasOwnProperty('send_as_user')) {
                obj['send_as_user'] = ApiClient.convertToType(data['send_as_user'], 'Number');
            }
            if (data.hasOwnProperty('reply_to_user')) {
                obj['reply_to_user'] = ApiClient.convertToType(data['reply_to_user'], 'Number');
            }
            if (data.hasOwnProperty('related_application')) {
                obj['related_application'] = ApiClient.convertToType(data['related_application'], 'Number');
            }
            if (data.hasOwnProperty('related_borrower')) {
                obj['related_borrower'] = ApiClient.convertToType(data['related_borrower'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ReminderRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ReminderRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ReminderRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['recipient_email'] && !(typeof data['recipient_email'] === 'string' || data['recipient_email'] instanceof String)) {
            throw new Error("Expected the field `recipient_email` to be a primitive type in the JSON string but got " + data['recipient_email']);
        }
        // ensure the json data is a string
        if (data['email_body'] && !(typeof data['email_body'] === 'string' || data['email_body'] instanceof String)) {
            throw new Error("Expected the field `email_body` to be a primitive type in the JSON string but got " + data['email_body']);
        }
        // ensure the json data is a string
        if (data['subject'] && !(typeof data['subject'] === 'string' || data['subject'] instanceof String)) {
            throw new Error("Expected the field `subject` to be a primitive type in the JSON string but got " + data['subject']);
        }

        return true;
    }


}

ReminderRequest.RequiredProperties = ["recipient_type", "recipient_email", "send_datetime", "email_body", "subject"];

/**
 * @member {module:models/RecipientTypeEnum} recipient_type
 */
ReminderRequest.prototype['recipient_type'] = undefined;

/**
 * @member {String} recipient_email
 */
ReminderRequest.prototype['recipient_email'] = undefined;

/**
 * @member {Date} send_datetime
 */
ReminderRequest.prototype['send_datetime'] = undefined;

/**
 * @member {String} email_body
 */
ReminderRequest.prototype['email_body'] = undefined;

/**
 * @member {String} subject
 */
ReminderRequest.prototype['subject'] = undefined;

/**
 * @member {Number} send_as_user
 */
ReminderRequest.prototype['send_as_user'] = undefined;

/**
 * @member {Number} reply_to_user
 */
ReminderRequest.prototype['reply_to_user'] = undefined;

/**
 * @member {Number} related_application
 */
ReminderRequest.prototype['related_application'] = undefined;

/**
 * @member {Number} related_borrower
 */
ReminderRequest.prototype['related_borrower'] = undefined;






export default ReminderRequest;

