/**
 * CRM Loan Management System API
 * A comprehensive CRM system for loan applications with fully synchronized frontend and backend development.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UsersAuthLoginCreate200Response model module.
 * @module models/UsersAuthLoginCreate200Response
 * @version 1.0.0
 */
class UsersAuthLoginCreate200Response {
    /**
     * Constructs a new <code>UsersAuthLoginCreate200Response</code>.
     * @alias module:models/UsersAuthLoginCreate200Response
     */
    constructor() { 
        
        UsersAuthLoginCreate200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UsersAuthLoginCreate200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/UsersAuthLoginCreate200Response} obj Optional instance to populate.
     * @return {module:models/UsersAuthLoginCreate200Response} The populated <code>UsersAuthLoginCreate200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsersAuthLoginCreate200Response();

            if (data.hasOwnProperty('refresh')) {
                obj['refresh'] = ApiClient.convertToType(data['refresh'], 'String');
            }
            if (data.hasOwnProperty('access')) {
                obj['access'] = ApiClient.convertToType(data['access'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UsersAuthLoginCreate200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsersAuthLoginCreate200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['refresh'] && !(typeof data['refresh'] === 'string' || data['refresh'] instanceof String)) {
            throw new Error("Expected the field `refresh` to be a primitive type in the JSON string but got " + data['refresh']);
        }
        // ensure the json data is a string
        if (data['access'] && !(typeof data['access'] === 'string' || data['access'] instanceof String)) {
            throw new Error("Expected the field `access` to be a primitive type in the JSON string but got " + data['access']);
        }

        return true;
    }


}



/**
 * @member {String} refresh
 */
UsersAuthLoginCreate200Response.prototype['refresh'] = undefined;

/**
 * @member {String} access
 */
UsersAuthLoginCreate200Response.prototype['access'] = undefined;






export default UsersAuthLoginCreate200Response;

